# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lxl/Documents/vitis_hls_ws/Project/Project/vivado_project/ORB_accel.srcs/sources_1/bd/ORB_accel/ip/ORB_accel_auto_pc_0/ORB_accel_auto_pc_0.xci
# IP: The module: 'ORB_accel_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lxl/Documents/vitis_hls_ws/Project/Project/vivado_project/ORB_accel.gen/sources_1/bd/ORB_accel/ip/ORB_accel_auto_pc_0/ORB_accel_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ORB_accel_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/lxl/Documents/vitis_hls_ws/Project/Project/vivado_project/ORB_accel.srcs/sources_1/bd/ORB_accel/ip/ORB_accel_auto_pc_0/ORB_accel_auto_pc_0.xci
# IP: The module: 'ORB_accel_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lxl/Documents/vitis_hls_ws/Project/Project/vivado_project/ORB_accel.gen/sources_1/bd/ORB_accel/ip/ORB_accel_auto_pc_0/ORB_accel_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ORB_accel_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
