// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ORB_accel_process_resize_8_0_1080_1920_1_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        img_mat_429_dout,
        img_mat_429_empty_n,
        img_mat_429_read,
        resized_mat_430_din,
        resized_mat_430_full_n,
        resized_mat_430_write,
        src_rows_dout,
        src_rows_empty_n,
        src_rows_read,
        src_cols_dout,
        src_cols_empty_n,
        src_cols_read,
        dst_rows_dout,
        dst_rows_empty_n,
        dst_rows_read,
        dst_cols_dout,
        dst_cols_empty_n,
        dst_cols_read,
        dst_rows_out_din,
        dst_rows_out_full_n,
        dst_rows_out_write,
        dst_cols_out_din,
        dst_cols_out_full_n,
        dst_cols_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] img_mat_429_dout;
input   img_mat_429_empty_n;
output   img_mat_429_read;
output  [7:0] resized_mat_430_din;
input   resized_mat_430_full_n;
output   resized_mat_430_write;
input  [10:0] src_rows_dout;
input   src_rows_empty_n;
output   src_rows_read;
input  [10:0] src_cols_dout;
input   src_cols_empty_n;
output   src_cols_read;
input  [10:0] dst_rows_dout;
input   dst_rows_empty_n;
output   dst_rows_read;
input  [10:0] dst_cols_dout;
input   dst_cols_empty_n;
output   dst_cols_read;
output  [10:0] dst_rows_out_din;
input   dst_rows_out_full_n;
output   dst_rows_out_write;
output  [10:0] dst_cols_out_din;
input   dst_cols_out_full_n;
output   dst_cols_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg img_mat_429_read;
reg resized_mat_430_write;
reg src_rows_read;
reg src_cols_read;
reg dst_rows_read;
reg dst_cols_read;
reg dst_rows_out_write;
reg dst_cols_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    src_rows_blk_n;
reg    src_cols_blk_n;
reg    dst_rows_blk_n;
reg    dst_cols_blk_n;
reg    dst_rows_out_blk_n;
reg    dst_cols_out_blk_n;
reg   [10:0] dst_rows_read_reg_96;
reg   [10:0] dst_cols_read_reg_101;
reg   [10:0] src_rows_read_reg_106;
reg   [10:0] src_cols_read_reg_111;
wire    grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_start;
wire    grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_done;
wire    grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_idle;
wire    grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_ready;
wire    grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_img_mat_429_read;
wire   [7:0] grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_resized_mat_430_din;
wire    grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_resized_mat_430_write;
reg    grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_start_reg;
reg    ap_block_state1_ignore_call16;
wire    ap_CS_fsm_state2;
reg    ap_block_state1;
reg   [1:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_start_reg = 1'b0;
end

ORB_accel_resize_1_0_1080_1920_1080_1920_1_8_s grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_start),
    .ap_done(grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_done),
    .ap_idle(grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_idle),
    .ap_ready(grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_ready),
    .img_mat_429_dout(img_mat_429_dout),
    .img_mat_429_empty_n(img_mat_429_empty_n),
    .img_mat_429_read(grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_img_mat_429_read),
    .resized_mat_430_din(grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_resized_mat_430_din),
    .resized_mat_430_full_n(resized_mat_430_full_n),
    .resized_mat_430_write(grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_resized_mat_430_write),
    .p_read(src_rows_read_reg_106),
    .p_read1(src_cols_read_reg_111),
    .p_read2(dst_rows_read_reg_96),
    .p_read3(dst_cols_read_reg_101)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_start_reg <= 1'b0;
    end else begin
        if ((~((real_start == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (dst_cols_empty_n == 1'b0) | (dst_rows_empty_n == 1'b0) | (src_cols_empty_n == 1'b0) | (src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_start_reg <= 1'b1;
        end else if ((grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_ready == 1'b1)) begin
            grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        dst_cols_read_reg_101 <= dst_cols_dout;
        dst_rows_read_reg_96 <= dst_rows_dout;
        src_cols_read_reg_111 <= src_cols_dout;
        src_rows_read_reg_106 <= src_rows_dout;
    end
end

always @ (*) begin
    if (((grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_cols_blk_n = dst_cols_empty_n;
    end else begin
        dst_cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_cols_out_blk_n = dst_cols_out_full_n;
    end else begin
        dst_cols_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (dst_cols_empty_n == 1'b0) | (dst_rows_empty_n == 1'b0) | (src_cols_empty_n == 1'b0) | (src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_cols_out_write = 1'b1;
    end else begin
        dst_cols_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (dst_cols_empty_n == 1'b0) | (dst_rows_empty_n == 1'b0) | (src_cols_empty_n == 1'b0) | (src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_cols_read = 1'b1;
    end else begin
        dst_cols_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_rows_blk_n = dst_rows_empty_n;
    end else begin
        dst_rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_rows_out_blk_n = dst_rows_out_full_n;
    end else begin
        dst_rows_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (dst_cols_empty_n == 1'b0) | (dst_rows_empty_n == 1'b0) | (src_cols_empty_n == 1'b0) | (src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_rows_out_write = 1'b1;
    end else begin
        dst_rows_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (dst_cols_empty_n == 1'b0) | (dst_rows_empty_n == 1'b0) | (src_cols_empty_n == 1'b0) | (src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dst_rows_read = 1'b1;
    end else begin
        dst_rows_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        img_mat_429_read = grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_img_mat_429_read;
    end else begin
        img_mat_429_read = 1'b0;
    end
end

always @ (*) begin
    if (((grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        resized_mat_430_write = grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_resized_mat_430_write;
    end else begin
        resized_mat_430_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_cols_blk_n = src_cols_empty_n;
    end else begin
        src_cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (dst_cols_empty_n == 1'b0) | (dst_rows_empty_n == 1'b0) | (src_cols_empty_n == 1'b0) | (src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_cols_read = 1'b1;
    end else begin
        src_cols_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_rows_blk_n = src_rows_empty_n;
    end else begin
        src_rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (dst_cols_empty_n == 1'b0) | (dst_rows_empty_n == 1'b0) | (src_cols_empty_n == 1'b0) | (src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_rows_read = 1'b1;
    end else begin
        src_rows_read = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (dst_cols_empty_n == 1'b0) | (dst_rows_empty_n == 1'b0) | (src_cols_empty_n == 1'b0) | (src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (dst_cols_empty_n == 1'b0) | (dst_rows_empty_n == 1'b0) | (src_cols_empty_n == 1'b0) | (src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call16 = ((real_start == 1'b0) | (dst_cols_out_full_n == 1'b0) | (dst_rows_out_full_n == 1'b0) | (dst_cols_empty_n == 1'b0) | (dst_rows_empty_n == 1'b0) | (src_cols_empty_n == 1'b0) | (src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign dst_cols_out_din = dst_cols_dout;

assign dst_rows_out_din = dst_rows_dout;

assign grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_start = grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_ap_start_reg;

assign resized_mat_430_din = grp_resize_1_0_1080_1920_1080_1920_1_8_s_fu_80_resized_mat_430_din;

assign start_out = real_start;

endmodule //ORB_accel_process_resize_8_0_1080_1920_1_s
