// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ORB_accel_fast_score (
        ap_clk,
        ap_rst,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_threshold,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [8:0] p_read1;
input  [8:0] p_read2;
input  [8:0] p_read3;
input  [8:0] p_read4;
input  [8:0] p_read5;
input  [8:0] p_read6;
input  [8:0] p_read7;
input  [8:0] p_read8;
input  [8:0] p_read9;
input  [8:0] p_read10;
input  [8:0] p_read11;
input  [8:0] p_read12;
input  [8:0] p_read13;
input  [8:0] p_read14;
input  [8:0] p_read15;
input  [8:0] p_read16;
input  [7:0] p_threshold;
output  [7:0] ap_return;
input   ap_ce;

reg[7:0] ap_return;

reg   [8:0] p_read_reg_1747;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg   [8:0] p_read_8_reg_1755;
reg   [8:0] p_read_8_reg_1755_pp0_iter1_reg;
reg   [8:0] p_read_8_reg_1755_pp0_iter2_reg;
reg   [8:0] p_read_9_reg_1763;
reg   [8:0] p_read_10_reg_1771;
reg   [8:0] p_read_10_reg_1771_pp0_iter1_reg;
reg   [8:0] p_read_11_reg_1779;
reg   [8:0] p_read_12_reg_1787;
reg   [8:0] p_read_12_reg_1787_pp0_iter1_reg;
reg   [8:0] p_read_14_reg_1795;
reg   [8:0] p_read_14_reg_1795_pp0_iter1_reg;
reg   [8:0] p_read814_reg_1803;
reg   [8:0] p_read814_reg_1803_pp0_iter1_reg;
reg   [8:0] p_read814_reg_1803_pp0_iter2_reg;
reg   [8:0] p_read713_reg_1811;
reg   [8:0] p_read612_reg_1819;
reg   [8:0] p_read612_reg_1819_pp0_iter1_reg;
reg   [8:0] p_read511_reg_1827;
reg   [8:0] p_read410_reg_1835;
reg   [8:0] p_read410_reg_1835_pp0_iter1_reg;
reg   [8:0] p_read39_reg_1843;
reg   [8:0] p_read28_reg_1849;
reg   [8:0] p_read28_reg_1849_pp0_iter1_reg;
wire   [8:0] select_ln27_1_fu_628_p3;
reg   [8:0] select_ln27_1_reg_1857;
wire   [8:0] select_ln28_1_fu_642_p3;
reg   [8:0] select_ln28_1_reg_1864;
wire   [8:0] select_ln27_2_fu_656_p3;
reg   [8:0] select_ln27_2_reg_1871;
wire   [8:0] select_ln28_2_fu_670_p3;
reg   [8:0] select_ln28_2_reg_1879;
wire   [8:0] select_ln27_3_fu_684_p3;
reg   [8:0] select_ln27_3_reg_1887;
wire   [8:0] select_ln28_3_fu_698_p3;
reg   [8:0] select_ln28_3_reg_1895;
wire   [8:0] select_ln27_4_fu_712_p3;
reg   [8:0] select_ln27_4_reg_1903;
reg   [8:0] select_ln27_4_reg_1903_pp0_iter1_reg;
wire   [8:0] select_ln28_4_fu_726_p3;
reg   [8:0] select_ln28_4_reg_1911;
reg   [8:0] select_ln28_4_reg_1911_pp0_iter1_reg;
wire   [8:0] select_ln27_5_fu_740_p3;
reg   [8:0] select_ln27_5_reg_1919;
reg   [8:0] select_ln27_5_reg_1919_pp0_iter1_reg;
wire   [8:0] select_ln28_5_fu_754_p3;
reg   [8:0] select_ln28_5_reg_1927;
reg   [8:0] select_ln28_5_reg_1927_pp0_iter1_reg;
wire   [8:0] select_ln27_6_fu_768_p3;
reg   [8:0] select_ln27_6_reg_1935;
reg   [8:0] select_ln27_6_reg_1935_pp0_iter1_reg;
wire   [8:0] select_ln28_6_fu_782_p3;
reg   [8:0] select_ln28_6_reg_1943;
reg   [8:0] select_ln28_6_reg_1943_pp0_iter1_reg;
wire   [8:0] select_ln27_7_fu_796_p3;
reg   [8:0] select_ln27_7_reg_1951;
reg   [8:0] select_ln27_7_reg_1951_pp0_iter1_reg;
reg   [8:0] select_ln27_7_reg_1951_pp0_iter2_reg;
wire   [8:0] select_ln28_7_fu_810_p3;
reg   [8:0] select_ln28_7_reg_1959;
reg   [8:0] select_ln28_7_reg_1959_pp0_iter1_reg;
reg   [8:0] select_ln28_7_reg_1959_pp0_iter2_reg;
wire   [7:0] select_ln36_8_fu_846_p3;
reg   [7:0] select_ln36_8_reg_1967;
wire   [0:0] icmp_ln37_1_fu_872_p2;
reg   [0:0] icmp_ln37_1_reg_1972;
wire   [7:0] trunc_ln37_fu_878_p1;
reg   [7:0] trunc_ln37_reg_1977;
wire   [0:0] icmp_ln36_8_fu_882_p2;
reg   [0:0] icmp_ln36_8_reg_1982;
wire   [8:0] select_ln43_1_fu_914_p3;
reg   [8:0] select_ln43_1_reg_1987;
wire   [8:0] select_ln44_fu_928_p3;
reg   [8:0] select_ln44_reg_1992;
wire   [0:0] icmp_ln44_2_fu_936_p2;
reg   [0:0] icmp_ln44_2_reg_1997;
wire   [0:0] icmp_ln43_8_fu_942_p2;
reg   [0:0] icmp_ln43_8_reg_2002;
wire   [7:0] select_ln36_11_fu_1100_p3;
reg   [7:0] select_ln36_11_reg_2007;
wire   [8:0] select_ln37_3_fu_1112_p3;
reg   [8:0] select_ln37_3_reg_2013;
wire   [7:0] trunc_ln37_3_fu_1118_p1;
reg   [7:0] trunc_ln37_3_reg_2018;
wire   [8:0] select_ln43_7_fu_1234_p3;
reg   [8:0] select_ln43_7_reg_2023;
wire   [8:0] select_ln44_6_fu_1246_p3;
reg   [8:0] select_ln44_6_reg_2029;
wire   [7:0] select_ln37_13_fu_1386_p3;
reg   [7:0] select_ln37_13_reg_2035;
wire   [0:0] icmp_ln36_14_fu_1408_p2;
reg   [0:0] icmp_ln36_14_reg_2040;
wire   [7:0] trunc_ln36_6_fu_1414_p1;
reg   [7:0] trunc_ln36_6_reg_2045;
wire   [8:0] select_ln37_6_fu_1422_p3;
reg   [8:0] select_ln37_6_reg_2050;
wire   [7:0] trunc_ln37_6_fu_1428_p1;
reg   [7:0] trunc_ln37_6_reg_2055;
wire   [8:0] select_ln44_11_fu_1530_p3;
reg   [8:0] select_ln44_11_reg_2060;
wire   [8:0] select_ln43_12_fu_1542_p3;
reg   [8:0] select_ln43_12_reg_2066;
wire   [8:0] select_ln44_12_fu_1552_p3;
reg   [8:0] select_ln44_12_reg_2072;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln17_fu_146_p2;
wire   [0:0] icmp_ln18_fu_160_p2;
wire   [0:0] icmp_ln17_1_fu_174_p2;
wire   [0:0] icmp_ln18_1_fu_188_p2;
wire   [0:0] icmp_ln17_2_fu_202_p2;
wire   [0:0] icmp_ln18_2_fu_216_p2;
wire   [0:0] icmp_ln17_3_fu_230_p2;
wire   [0:0] icmp_ln18_3_fu_244_p2;
wire   [0:0] icmp_ln17_4_fu_258_p2;
wire   [0:0] icmp_ln18_4_fu_272_p2;
wire   [0:0] icmp_ln17_5_fu_286_p2;
wire   [0:0] icmp_ln18_5_fu_300_p2;
wire   [0:0] icmp_ln17_6_fu_314_p2;
wire   [0:0] icmp_ln18_6_fu_328_p2;
wire   [0:0] icmp_ln17_7_fu_342_p2;
wire   [0:0] icmp_ln18_7_fu_356_p2;
wire   [8:0] select_ln17_fu_152_p3;
wire   [8:0] select_ln17_1_fu_180_p3;
wire   [0:0] icmp_ln22_fu_370_p2;
wire   [8:0] select_ln18_fu_166_p3;
wire   [8:0] select_ln18_1_fu_194_p3;
wire   [0:0] icmp_ln23_fu_384_p2;
wire   [8:0] select_ln17_2_fu_208_p3;
wire   [0:0] icmp_ln22_1_fu_398_p2;
wire   [8:0] select_ln18_2_fu_222_p3;
wire   [0:0] icmp_ln23_1_fu_412_p2;
wire   [8:0] select_ln17_3_fu_236_p3;
wire   [0:0] icmp_ln22_2_fu_426_p2;
wire   [8:0] select_ln18_3_fu_250_p3;
wire   [0:0] icmp_ln23_2_fu_440_p2;
wire   [8:0] select_ln17_4_fu_264_p3;
wire   [0:0] icmp_ln22_3_fu_454_p2;
wire   [8:0] select_ln18_4_fu_278_p3;
wire   [0:0] icmp_ln23_3_fu_468_p2;
wire   [8:0] select_ln17_5_fu_292_p3;
wire   [0:0] icmp_ln22_4_fu_482_p2;
wire   [8:0] select_ln18_5_fu_306_p3;
wire   [0:0] icmp_ln23_4_fu_496_p2;
wire   [8:0] select_ln17_6_fu_320_p3;
wire   [0:0] icmp_ln22_5_fu_510_p2;
wire   [8:0] select_ln18_6_fu_334_p3;
wire   [0:0] icmp_ln23_5_fu_524_p2;
wire   [8:0] select_ln17_7_fu_348_p3;
wire   [0:0] icmp_ln22_6_fu_538_p2;
wire   [8:0] select_ln18_7_fu_362_p3;
wire   [0:0] icmp_ln23_6_fu_552_p2;
wire   [0:0] icmp_ln22_7_fu_566_p2;
wire   [0:0] icmp_ln23_7_fu_580_p2;
wire   [8:0] select_ln22_fu_376_p3;
wire   [8:0] select_ln22_2_fu_432_p3;
wire   [0:0] icmp_ln27_fu_594_p2;
wire   [8:0] select_ln23_fu_390_p3;
wire   [8:0] select_ln23_2_fu_446_p3;
wire   [0:0] icmp_ln28_fu_608_p2;
wire   [8:0] select_ln22_1_fu_404_p3;
wire   [8:0] select_ln22_3_fu_460_p3;
wire   [0:0] icmp_ln27_1_fu_622_p2;
wire   [8:0] select_ln23_1_fu_418_p3;
wire   [8:0] select_ln23_3_fu_474_p3;
wire   [0:0] icmp_ln28_1_fu_636_p2;
wire   [8:0] select_ln22_4_fu_488_p3;
wire   [0:0] icmp_ln27_2_fu_650_p2;
wire   [8:0] select_ln23_4_fu_502_p3;
wire   [0:0] icmp_ln28_2_fu_664_p2;
wire   [8:0] select_ln22_5_fu_516_p3;
wire   [0:0] icmp_ln27_3_fu_678_p2;
wire   [8:0] select_ln23_5_fu_530_p3;
wire   [0:0] icmp_ln28_3_fu_692_p2;
wire   [8:0] select_ln22_6_fu_544_p3;
wire   [0:0] icmp_ln27_4_fu_706_p2;
wire   [8:0] select_ln23_6_fu_558_p3;
wire   [0:0] icmp_ln28_4_fu_720_p2;
wire   [8:0] select_ln22_7_fu_572_p3;
wire   [0:0] icmp_ln27_5_fu_734_p2;
wire   [8:0] select_ln23_7_fu_586_p3;
wire   [0:0] icmp_ln28_5_fu_748_p2;
wire   [0:0] icmp_ln27_6_fu_762_p2;
wire   [0:0] icmp_ln28_6_fu_776_p2;
wire   [0:0] icmp_ln27_7_fu_790_p2;
wire   [0:0] icmp_ln28_7_fu_804_p2;
wire   [8:0] select_ln27_fu_600_p3;
wire   [0:0] icmp_ln36_fu_822_p2;
wire   [8:0] zext_ln36_fu_818_p1;
wire   [8:0] select_ln36_fu_828_p3;
wire   [0:0] icmp_ln36_1_fu_836_p2;
wire   [7:0] trunc_ln36_fu_842_p1;
wire   [0:0] icmp_ln37_fu_858_p2;
wire   [8:0] zext_ln37_fu_854_p1;
wire   [8:0] select_ln37_fu_864_p3;
wire   [8:0] select_ln28_fu_614_p3;
wire   [0:0] icmp_ln43_fu_894_p2;
wire   [8:0] select_ln43_fu_900_p3;
wire   [8:0] b0_fu_888_p2;
wire   [0:0] icmp_ln43_1_fu_908_p2;
wire   [0:0] icmp_ln44_fu_922_p2;
wire   [7:0] select_ln37_1_fu_948_p3;
wire   [8:0] zext_ln36_1_fu_953_p1;
wire   [8:0] select_ln36_1_fu_957_p3;
wire   [0:0] icmp_ln36_9_fu_962_p2;
wire   [7:0] trunc_ln36_1_fu_968_p1;
wire   [7:0] select_ln36_9_fu_972_p3;
wire   [0:0] icmp_ln37_8_fu_984_p2;
wire   [8:0] zext_ln37_1_fu_980_p1;
wire   [8:0] select_ln37_8_fu_988_p3;
wire   [0:0] icmp_ln37_9_fu_994_p2;
wire   [7:0] trunc_ln37_1_fu_1000_p1;
wire   [7:0] select_ln37_9_fu_1004_p3;
wire   [0:0] icmp_ln36_2_fu_1016_p2;
wire   [8:0] zext_ln36_2_fu_1012_p1;
wire   [8:0] select_ln36_2_fu_1020_p3;
wire   [0:0] icmp_ln36_10_fu_1026_p2;
wire   [7:0] trunc_ln36_2_fu_1032_p1;
wire   [7:0] select_ln36_10_fu_1036_p3;
wire   [0:0] icmp_ln37_2_fu_1048_p2;
wire   [8:0] zext_ln37_2_fu_1044_p1;
wire   [8:0] select_ln37_2_fu_1052_p3;
wire   [0:0] icmp_ln37_10_fu_1058_p2;
wire   [7:0] trunc_ln37_2_fu_1064_p1;
wire   [7:0] select_ln37_10_fu_1068_p3;
wire   [0:0] icmp_ln36_3_fu_1080_p2;
wire   [8:0] zext_ln36_3_fu_1076_p1;
wire   [8:0] select_ln36_3_fu_1084_p3;
wire   [0:0] icmp_ln36_11_fu_1090_p2;
wire   [7:0] trunc_ln36_3_fu_1096_p1;
wire   [0:0] icmp_ln37_3_fu_1108_p2;
wire   [8:0] select_ln44_1_fu_1122_p3;
wire   [8:0] select_ln43_2_fu_1127_p3;
wire   [0:0] icmp_ln43_9_fu_1132_p2;
wire   [0:0] icmp_ln44_1_fu_1146_p2;
wire   [8:0] select_ln43_3_fu_1138_p3;
wire   [8:0] select_ln44_2_fu_1150_p3;
wire   [0:0] icmp_ln44_8_fu_1156_p2;
wire   [0:0] icmp_ln43_2_fu_1170_p2;
wire   [8:0] select_ln44_3_fu_1162_p3;
wire   [8:0] select_ln43_4_fu_1174_p3;
wire   [0:0] icmp_ln43_10_fu_1180_p2;
wire   [0:0] icmp_ln44_9_fu_1194_p2;
wire   [8:0] select_ln43_5_fu_1186_p3;
wire   [8:0] select_ln44_4_fu_1198_p3;
wire   [0:0] icmp_ln44_10_fu_1204_p2;
wire   [0:0] icmp_ln43_3_fu_1218_p2;
wire   [8:0] select_ln44_5_fu_1210_p3;
wire   [8:0] select_ln43_6_fu_1222_p3;
wire   [0:0] icmp_ln43_11_fu_1228_p2;
wire   [0:0] icmp_ln44_3_fu_1242_p2;
wire   [8:0] zext_ln37_3_fu_1252_p1;
wire   [0:0] icmp_ln37_11_fu_1255_p2;
wire   [7:0] select_ln37_11_fu_1260_p3;
wire   [0:0] icmp_ln36_4_fu_1270_p2;
wire   [8:0] zext_ln36_4_fu_1266_p1;
wire   [8:0] select_ln36_4_fu_1274_p3;
wire   [0:0] icmp_ln36_12_fu_1280_p2;
wire   [7:0] trunc_ln36_4_fu_1286_p1;
wire   [7:0] select_ln36_12_fu_1290_p3;
wire   [0:0] icmp_ln37_4_fu_1302_p2;
wire   [8:0] zext_ln37_4_fu_1298_p1;
wire   [8:0] select_ln37_4_fu_1306_p3;
wire   [0:0] icmp_ln37_12_fu_1312_p2;
wire   [7:0] trunc_ln37_4_fu_1318_p1;
wire   [7:0] select_ln37_12_fu_1322_p3;
wire   [0:0] icmp_ln36_5_fu_1334_p2;
wire   [8:0] zext_ln36_5_fu_1330_p1;
wire   [8:0] select_ln36_5_fu_1338_p3;
wire   [0:0] icmp_ln36_13_fu_1344_p2;
wire   [7:0] trunc_ln36_5_fu_1350_p1;
wire   [7:0] select_ln36_13_fu_1354_p3;
wire   [0:0] icmp_ln37_5_fu_1366_p2;
wire   [8:0] zext_ln37_5_fu_1362_p1;
wire   [8:0] select_ln37_5_fu_1370_p3;
wire   [0:0] icmp_ln37_13_fu_1376_p2;
wire   [7:0] trunc_ln37_5_fu_1382_p1;
wire   [0:0] icmp_ln36_6_fu_1398_p2;
wire   [8:0] zext_ln36_6_fu_1394_p1;
wire   [8:0] select_ln36_6_fu_1402_p3;
wire   [0:0] icmp_ln37_6_fu_1418_p2;
wire   [0:0] icmp_ln44_11_fu_1432_p2;
wire   [0:0] icmp_ln43_4_fu_1442_p2;
wire   [8:0] select_ln44_7_fu_1436_p3;
wire   [8:0] select_ln43_8_fu_1446_p3;
wire   [0:0] icmp_ln43_12_fu_1452_p2;
wire   [0:0] icmp_ln44_4_fu_1466_p2;
wire   [8:0] select_ln43_9_fu_1458_p3;
wire   [8:0] select_ln44_8_fu_1470_p3;
wire   [0:0] icmp_ln44_12_fu_1476_p2;
wire   [0:0] icmp_ln43_5_fu_1490_p2;
wire   [8:0] select_ln44_9_fu_1482_p3;
wire   [8:0] select_ln43_10_fu_1494_p3;
wire   [0:0] icmp_ln43_13_fu_1500_p2;
wire   [0:0] icmp_ln44_5_fu_1514_p2;
wire   [8:0] select_ln43_11_fu_1506_p3;
wire   [8:0] select_ln44_10_fu_1518_p3;
wire   [0:0] icmp_ln44_13_fu_1524_p2;
wire   [0:0] icmp_ln43_6_fu_1538_p2;
wire   [0:0] icmp_ln44_6_fu_1548_p2;
wire   [7:0] select_ln36_14_fu_1558_p3;
wire   [8:0] zext_ln37_6_fu_1563_p1;
wire   [0:0] icmp_ln37_14_fu_1567_p2;
wire   [7:0] select_ln37_14_fu_1572_p3;
wire   [0:0] icmp_ln36_7_fu_1583_p2;
wire   [8:0] zext_ln36_7_fu_1579_p1;
wire   [8:0] select_ln36_7_fu_1587_p3;
wire   [0:0] icmp_ln36_15_fu_1593_p2;
wire   [7:0] trunc_ln36_7_fu_1599_p1;
wire   [7:0] select_ln36_15_fu_1603_p3;
wire   [0:0] icmp_ln37_7_fu_1615_p2;
wire   [8:0] zext_ln37_7_fu_1611_p1;
wire   [8:0] select_ln37_7_fu_1619_p3;
wire   [0:0] icmp_ln37_15_fu_1625_p2;
wire   [7:0] trunc_ln37_7_fu_1631_p1;
wire   [0:0] icmp_ln43_14_fu_1643_p2;
wire   [8:0] select_ln43_13_fu_1647_p3;
wire   [0:0] icmp_ln44_14_fu_1653_p2;
wire   [0:0] icmp_ln43_7_fu_1665_p2;
wire   [8:0] select_ln44_13_fu_1658_p3;
wire   [8:0] select_ln43_14_fu_1669_p3;
wire   [0:0] icmp_ln43_15_fu_1675_p2;
wire   [0:0] icmp_ln44_7_fu_1689_p2;
wire   [8:0] select_ln43_15_fu_1681_p3;
wire   [8:0] select_ln44_14_fu_1693_p3;
wire   [0:0] icmp_ln44_15_fu_1699_p2;
wire   [7:0] trunc_ln44_fu_1705_p1;
wire   [7:0] trunc_ln44_1_fu_1709_p1;
wire   [7:0] select_ln44_15_fu_1713_p3;
wire   [7:0] select_ln37_15_fu_1635_p3;
wire   [7:0] sub_ln46_fu_1721_p2;
wire   [0:0] icmp_ln46_fu_1727_p2;
wire   [7:0] select_ln46_fu_1733_p3;
wire   [7:0] score_V_fu_1741_p2;
reg    ap_ce_reg;
reg   [8:0] p_read1_int_reg;
reg   [8:0] p_read2_int_reg;
reg   [8:0] p_read3_int_reg;
reg   [8:0] p_read4_int_reg;
reg   [8:0] p_read5_int_reg;
reg   [8:0] p_read6_int_reg;
reg   [8:0] p_read7_int_reg;
reg   [8:0] p_read8_int_reg;
reg   [8:0] p_read9_int_reg;
reg   [8:0] p_read10_int_reg;
reg   [8:0] p_read11_int_reg;
reg   [8:0] p_read12_int_reg;
reg   [8:0] p_read13_int_reg;
reg   [8:0] p_read14_int_reg;
reg   [8:0] p_read15_int_reg;
reg   [8:0] p_read16_int_reg;
reg   [7:0] p_threshold_int_reg;
reg   [7:0] ap_return_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= score_V_fu_1741_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        icmp_ln36_14_reg_2040 <= icmp_ln36_14_fu_1408_p2;
        icmp_ln36_8_reg_1982 <= icmp_ln36_8_fu_882_p2;
        icmp_ln37_1_reg_1972 <= icmp_ln37_1_fu_872_p2;
        icmp_ln43_8_reg_2002 <= icmp_ln43_8_fu_942_p2;
        icmp_ln44_2_reg_1997 <= icmp_ln44_2_fu_936_p2;
        p_read28_reg_1849 <= p_read2_int_reg;
        p_read28_reg_1849_pp0_iter1_reg <= p_read28_reg_1849;
        p_read39_reg_1843 <= p_read3_int_reg;
        p_read410_reg_1835 <= p_read4_int_reg;
        p_read410_reg_1835_pp0_iter1_reg <= p_read410_reg_1835;
        p_read511_reg_1827 <= p_read5_int_reg;
        p_read612_reg_1819 <= p_read6_int_reg;
        p_read612_reg_1819_pp0_iter1_reg <= p_read612_reg_1819;
        p_read713_reg_1811 <= p_read7_int_reg;
        p_read814_reg_1803 <= p_read8_int_reg;
        p_read814_reg_1803_pp0_iter1_reg <= p_read814_reg_1803;
        p_read814_reg_1803_pp0_iter2_reg <= p_read814_reg_1803_pp0_iter1_reg;
        p_read_10_reg_1771 <= p_read13_int_reg;
        p_read_10_reg_1771_pp0_iter1_reg <= p_read_10_reg_1771;
        p_read_11_reg_1779 <= p_read12_int_reg;
        p_read_12_reg_1787 <= p_read11_int_reg;
        p_read_12_reg_1787_pp0_iter1_reg <= p_read_12_reg_1787;
        p_read_14_reg_1795 <= p_read9_int_reg;
        p_read_14_reg_1795_pp0_iter1_reg <= p_read_14_reg_1795;
        p_read_8_reg_1755 <= p_read15_int_reg;
        p_read_8_reg_1755_pp0_iter1_reg <= p_read_8_reg_1755;
        p_read_8_reg_1755_pp0_iter2_reg <= p_read_8_reg_1755_pp0_iter1_reg;
        p_read_9_reg_1763 <= p_read14_int_reg;
        p_read_reg_1747 <= p_read16_int_reg;
        select_ln27_1_reg_1857 <= select_ln27_1_fu_628_p3;
        select_ln27_2_reg_1871 <= select_ln27_2_fu_656_p3;
        select_ln27_3_reg_1887 <= select_ln27_3_fu_684_p3;
        select_ln27_4_reg_1903 <= select_ln27_4_fu_712_p3;
        select_ln27_4_reg_1903_pp0_iter1_reg <= select_ln27_4_reg_1903;
        select_ln27_5_reg_1919 <= select_ln27_5_fu_740_p3;
        select_ln27_5_reg_1919_pp0_iter1_reg <= select_ln27_5_reg_1919;
        select_ln27_6_reg_1935 <= select_ln27_6_fu_768_p3;
        select_ln27_6_reg_1935_pp0_iter1_reg <= select_ln27_6_reg_1935;
        select_ln27_7_reg_1951 <= select_ln27_7_fu_796_p3;
        select_ln27_7_reg_1951_pp0_iter1_reg <= select_ln27_7_reg_1951;
        select_ln27_7_reg_1951_pp0_iter2_reg <= select_ln27_7_reg_1951_pp0_iter1_reg;
        select_ln28_1_reg_1864 <= select_ln28_1_fu_642_p3;
        select_ln28_2_reg_1879 <= select_ln28_2_fu_670_p3;
        select_ln28_3_reg_1895 <= select_ln28_3_fu_698_p3;
        select_ln28_4_reg_1911 <= select_ln28_4_fu_726_p3;
        select_ln28_4_reg_1911_pp0_iter1_reg <= select_ln28_4_reg_1911;
        select_ln28_5_reg_1927 <= select_ln28_5_fu_754_p3;
        select_ln28_5_reg_1927_pp0_iter1_reg <= select_ln28_5_reg_1927;
        select_ln28_6_reg_1943 <= select_ln28_6_fu_782_p3;
        select_ln28_6_reg_1943_pp0_iter1_reg <= select_ln28_6_reg_1943;
        select_ln28_7_reg_1959 <= select_ln28_7_fu_810_p3;
        select_ln28_7_reg_1959_pp0_iter1_reg <= select_ln28_7_reg_1959;
        select_ln28_7_reg_1959_pp0_iter2_reg <= select_ln28_7_reg_1959_pp0_iter1_reg;
        select_ln36_11_reg_2007 <= select_ln36_11_fu_1100_p3;
        select_ln36_8_reg_1967 <= select_ln36_8_fu_846_p3;
        select_ln37_13_reg_2035 <= select_ln37_13_fu_1386_p3;
        select_ln37_3_reg_2013 <= select_ln37_3_fu_1112_p3;
        select_ln37_6_reg_2050 <= select_ln37_6_fu_1422_p3;
        select_ln43_12_reg_2066 <= select_ln43_12_fu_1542_p3;
        select_ln43_1_reg_1987 <= select_ln43_1_fu_914_p3;
        select_ln43_7_reg_2023 <= select_ln43_7_fu_1234_p3;
        select_ln44_11_reg_2060 <= select_ln44_11_fu_1530_p3;
        select_ln44_12_reg_2072 <= select_ln44_12_fu_1552_p3;
        select_ln44_6_reg_2029 <= select_ln44_6_fu_1246_p3;
        select_ln44_reg_1992 <= select_ln44_fu_928_p3;
        trunc_ln36_6_reg_2045 <= trunc_ln36_6_fu_1414_p1;
        trunc_ln37_3_reg_2018 <= trunc_ln37_3_fu_1118_p1;
        trunc_ln37_6_reg_2055 <= trunc_ln37_6_fu_1428_p1;
        trunc_ln37_reg_1977 <= trunc_ln37_fu_878_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read10_int_reg <= p_read10;
        p_read11_int_reg <= p_read11;
        p_read12_int_reg <= p_read12;
        p_read13_int_reg <= p_read13;
        p_read14_int_reg <= p_read14;
        p_read15_int_reg <= p_read15;
        p_read16_int_reg <= p_read16;
        p_read1_int_reg <= p_read1;
        p_read2_int_reg <= p_read2;
        p_read3_int_reg <= p_read3;
        p_read4_int_reg <= p_read4;
        p_read5_int_reg <= p_read5;
        p_read6_int_reg <= p_read6;
        p_read7_int_reg <= p_read7;
        p_read8_int_reg <= p_read8;
        p_read9_int_reg <= p_read9;
        p_threshold_int_reg <= p_threshold;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = score_V_fu_1741_p2;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign b0_fu_888_p2 = (9'd0 - zext_ln36_fu_818_p1);

assign icmp_ln17_1_fu_174_p2 = (($signed(p_read4_int_reg) < $signed(p_read5_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln17_2_fu_202_p2 = (($signed(p_read6_int_reg) < $signed(p_read7_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln17_3_fu_230_p2 = (($signed(p_read8_int_reg) < $signed(p_read9_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln17_4_fu_258_p2 = (($signed(p_read10_int_reg) < $signed(p_read11_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln17_5_fu_286_p2 = (($signed(p_read12_int_reg) < $signed(p_read13_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln17_6_fu_314_p2 = (($signed(p_read14_int_reg) < $signed(p_read15_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln17_7_fu_342_p2 = (($signed(p_read16_int_reg) < $signed(p_read1_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_146_p2 = (($signed(p_read2_int_reg) < $signed(p_read3_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln18_1_fu_188_p2 = (($signed(p_read4_int_reg) > $signed(p_read5_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln18_2_fu_216_p2 = (($signed(p_read6_int_reg) > $signed(p_read7_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln18_3_fu_244_p2 = (($signed(p_read8_int_reg) > $signed(p_read9_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln18_4_fu_272_p2 = (($signed(p_read10_int_reg) > $signed(p_read11_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln18_5_fu_300_p2 = (($signed(p_read12_int_reg) > $signed(p_read13_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln18_6_fu_328_p2 = (($signed(p_read14_int_reg) > $signed(p_read15_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln18_7_fu_356_p2 = (($signed(p_read16_int_reg) > $signed(p_read1_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_160_p2 = (($signed(p_read2_int_reg) > $signed(p_read3_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln22_1_fu_398_p2 = (($signed(select_ln17_1_fu_180_p3) < $signed(select_ln17_2_fu_208_p3)) ? 1'b1 : 1'b0);

assign icmp_ln22_2_fu_426_p2 = (($signed(select_ln17_2_fu_208_p3) < $signed(select_ln17_3_fu_236_p3)) ? 1'b1 : 1'b0);

assign icmp_ln22_3_fu_454_p2 = (($signed(select_ln17_3_fu_236_p3) < $signed(select_ln17_4_fu_264_p3)) ? 1'b1 : 1'b0);

assign icmp_ln22_4_fu_482_p2 = (($signed(select_ln17_4_fu_264_p3) < $signed(select_ln17_5_fu_292_p3)) ? 1'b1 : 1'b0);

assign icmp_ln22_5_fu_510_p2 = (($signed(select_ln17_5_fu_292_p3) < $signed(select_ln17_6_fu_320_p3)) ? 1'b1 : 1'b0);

assign icmp_ln22_6_fu_538_p2 = (($signed(select_ln17_6_fu_320_p3) < $signed(select_ln17_7_fu_348_p3)) ? 1'b1 : 1'b0);

assign icmp_ln22_7_fu_566_p2 = (($signed(select_ln17_7_fu_348_p3) < $signed(select_ln17_fu_152_p3)) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_370_p2 = (($signed(select_ln17_fu_152_p3) < $signed(select_ln17_1_fu_180_p3)) ? 1'b1 : 1'b0);

assign icmp_ln23_1_fu_412_p2 = (($signed(select_ln18_1_fu_194_p3) > $signed(select_ln18_2_fu_222_p3)) ? 1'b1 : 1'b0);

assign icmp_ln23_2_fu_440_p2 = (($signed(select_ln18_2_fu_222_p3) > $signed(select_ln18_3_fu_250_p3)) ? 1'b1 : 1'b0);

assign icmp_ln23_3_fu_468_p2 = (($signed(select_ln18_3_fu_250_p3) > $signed(select_ln18_4_fu_278_p3)) ? 1'b1 : 1'b0);

assign icmp_ln23_4_fu_496_p2 = (($signed(select_ln18_4_fu_278_p3) > $signed(select_ln18_5_fu_306_p3)) ? 1'b1 : 1'b0);

assign icmp_ln23_5_fu_524_p2 = (($signed(select_ln18_5_fu_306_p3) > $signed(select_ln18_6_fu_334_p3)) ? 1'b1 : 1'b0);

assign icmp_ln23_6_fu_552_p2 = (($signed(select_ln18_6_fu_334_p3) > $signed(select_ln18_7_fu_362_p3)) ? 1'b1 : 1'b0);

assign icmp_ln23_7_fu_580_p2 = (($signed(select_ln18_7_fu_362_p3) > $signed(select_ln18_fu_166_p3)) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_384_p2 = (($signed(select_ln18_fu_166_p3) > $signed(select_ln18_1_fu_194_p3)) ? 1'b1 : 1'b0);

assign icmp_ln27_1_fu_622_p2 = (($signed(select_ln22_1_fu_404_p3) < $signed(select_ln22_3_fu_460_p3)) ? 1'b1 : 1'b0);

assign icmp_ln27_2_fu_650_p2 = (($signed(select_ln22_2_fu_432_p3) < $signed(select_ln22_4_fu_488_p3)) ? 1'b1 : 1'b0);

assign icmp_ln27_3_fu_678_p2 = (($signed(select_ln22_3_fu_460_p3) < $signed(select_ln22_5_fu_516_p3)) ? 1'b1 : 1'b0);

assign icmp_ln27_4_fu_706_p2 = (($signed(select_ln22_4_fu_488_p3) < $signed(select_ln22_6_fu_544_p3)) ? 1'b1 : 1'b0);

assign icmp_ln27_5_fu_734_p2 = (($signed(select_ln22_5_fu_516_p3) < $signed(select_ln22_7_fu_572_p3)) ? 1'b1 : 1'b0);

assign icmp_ln27_6_fu_762_p2 = (($signed(select_ln22_6_fu_544_p3) < $signed(select_ln22_fu_376_p3)) ? 1'b1 : 1'b0);

assign icmp_ln27_7_fu_790_p2 = (($signed(select_ln22_7_fu_572_p3) < $signed(select_ln22_1_fu_404_p3)) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_594_p2 = (($signed(select_ln22_fu_376_p3) < $signed(select_ln22_2_fu_432_p3)) ? 1'b1 : 1'b0);

assign icmp_ln28_1_fu_636_p2 = (($signed(select_ln23_1_fu_418_p3) > $signed(select_ln23_3_fu_474_p3)) ? 1'b1 : 1'b0);

assign icmp_ln28_2_fu_664_p2 = (($signed(select_ln23_2_fu_446_p3) > $signed(select_ln23_4_fu_502_p3)) ? 1'b1 : 1'b0);

assign icmp_ln28_3_fu_692_p2 = (($signed(select_ln23_3_fu_474_p3) > $signed(select_ln23_5_fu_530_p3)) ? 1'b1 : 1'b0);

assign icmp_ln28_4_fu_720_p2 = (($signed(select_ln23_4_fu_502_p3) > $signed(select_ln23_6_fu_558_p3)) ? 1'b1 : 1'b0);

assign icmp_ln28_5_fu_748_p2 = (($signed(select_ln23_5_fu_530_p3) > $signed(select_ln23_7_fu_586_p3)) ? 1'b1 : 1'b0);

assign icmp_ln28_6_fu_776_p2 = (($signed(select_ln23_6_fu_558_p3) > $signed(select_ln23_fu_390_p3)) ? 1'b1 : 1'b0);

assign icmp_ln28_7_fu_804_p2 = (($signed(select_ln23_7_fu_586_p3) > $signed(select_ln23_1_fu_418_p3)) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_608_p2 = (($signed(select_ln23_fu_390_p3) > $signed(select_ln23_2_fu_446_p3)) ? 1'b1 : 1'b0);

assign icmp_ln36_10_fu_1026_p2 = (($signed(zext_ln36_2_fu_1012_p1) > $signed(select_ln36_2_fu_1020_p3)) ? 1'b1 : 1'b0);

assign icmp_ln36_11_fu_1090_p2 = (($signed(zext_ln36_3_fu_1076_p1) > $signed(select_ln36_3_fu_1084_p3)) ? 1'b1 : 1'b0);

assign icmp_ln36_12_fu_1280_p2 = (($signed(zext_ln36_4_fu_1266_p1) > $signed(select_ln36_4_fu_1274_p3)) ? 1'b1 : 1'b0);

assign icmp_ln36_13_fu_1344_p2 = (($signed(zext_ln36_5_fu_1330_p1) > $signed(select_ln36_5_fu_1338_p3)) ? 1'b1 : 1'b0);

assign icmp_ln36_14_fu_1408_p2 = (($signed(zext_ln36_6_fu_1394_p1) > $signed(select_ln36_6_fu_1402_p3)) ? 1'b1 : 1'b0);

assign icmp_ln36_15_fu_1593_p2 = (($signed(zext_ln36_7_fu_1579_p1) > $signed(select_ln36_7_fu_1587_p3)) ? 1'b1 : 1'b0);

assign icmp_ln36_1_fu_836_p2 = (($signed(zext_ln36_fu_818_p1) > $signed(select_ln36_fu_828_p3)) ? 1'b1 : 1'b0);

assign icmp_ln36_2_fu_1016_p2 = (($signed(select_ln27_2_reg_1871) < $signed(p_read511_reg_1827)) ? 1'b1 : 1'b0);

assign icmp_ln36_3_fu_1080_p2 = (($signed(select_ln27_3_reg_1887) < $signed(p_read713_reg_1811)) ? 1'b1 : 1'b0);

assign icmp_ln36_4_fu_1270_p2 = (($signed(select_ln27_4_reg_1903_pp0_iter1_reg) < $signed(p_read_14_reg_1795_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln36_5_fu_1334_p2 = (($signed(select_ln27_5_reg_1919_pp0_iter1_reg) < $signed(p_read_12_reg_1787_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln36_6_fu_1398_p2 = (($signed(select_ln27_6_reg_1935_pp0_iter1_reg) < $signed(p_read_10_reg_1771_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln36_7_fu_1583_p2 = (($signed(select_ln27_7_reg_1951_pp0_iter2_reg) < $signed(p_read_8_reg_1755_pp0_iter2_reg)) ? 1'b1 : 1'b0);

assign icmp_ln36_8_fu_882_p2 = (($signed(select_ln27_1_fu_628_p3) < $signed(p_read3_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln36_9_fu_962_p2 = (($signed(zext_ln36_1_fu_953_p1) > $signed(select_ln36_1_fu_957_p3)) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_822_p2 = (($signed(select_ln27_fu_600_p3) < $signed(p_read1_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln37_10_fu_1058_p2 = (($signed(zext_ln37_2_fu_1044_p1) > $signed(select_ln37_2_fu_1052_p3)) ? 1'b1 : 1'b0);

assign icmp_ln37_11_fu_1255_p2 = (($signed(zext_ln37_3_fu_1252_p1) > $signed(select_ln37_3_reg_2013)) ? 1'b1 : 1'b0);

assign icmp_ln37_12_fu_1312_p2 = (($signed(zext_ln37_4_fu_1298_p1) > $signed(select_ln37_4_fu_1306_p3)) ? 1'b1 : 1'b0);

assign icmp_ln37_13_fu_1376_p2 = (($signed(zext_ln37_5_fu_1362_p1) > $signed(select_ln37_5_fu_1370_p3)) ? 1'b1 : 1'b0);

assign icmp_ln37_14_fu_1567_p2 = (($signed(zext_ln37_6_fu_1563_p1) > $signed(select_ln37_6_reg_2050)) ? 1'b1 : 1'b0);

assign icmp_ln37_15_fu_1625_p2 = (($signed(zext_ln37_7_fu_1611_p1) > $signed(select_ln37_7_fu_1619_p3)) ? 1'b1 : 1'b0);

assign icmp_ln37_1_fu_872_p2 = (($signed(zext_ln37_fu_854_p1) > $signed(select_ln37_fu_864_p3)) ? 1'b1 : 1'b0);

assign icmp_ln37_2_fu_1048_p2 = (($signed(select_ln27_2_reg_1871) < $signed(p_read_9_reg_1763)) ? 1'b1 : 1'b0);

assign icmp_ln37_3_fu_1108_p2 = (($signed(select_ln27_3_reg_1887) < $signed(p_read_reg_1747)) ? 1'b1 : 1'b0);

assign icmp_ln37_4_fu_1302_p2 = (($signed(select_ln27_4_reg_1903_pp0_iter1_reg) < $signed(p_read28_reg_1849_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln37_5_fu_1366_p2 = (($signed(select_ln27_5_reg_1919_pp0_iter1_reg) < $signed(p_read410_reg_1835_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln37_6_fu_1418_p2 = (($signed(select_ln27_6_reg_1935_pp0_iter1_reg) < $signed(p_read612_reg_1819_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln37_7_fu_1615_p2 = (($signed(select_ln27_7_reg_1951_pp0_iter2_reg) < $signed(p_read814_reg_1803_pp0_iter2_reg)) ? 1'b1 : 1'b0);

assign icmp_ln37_8_fu_984_p2 = (($signed(select_ln27_1_reg_1857) < $signed(p_read_11_reg_1779)) ? 1'b1 : 1'b0);

assign icmp_ln37_9_fu_994_p2 = (($signed(zext_ln37_1_fu_980_p1) > $signed(select_ln37_8_fu_988_p3)) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_858_p2 = (($signed(select_ln27_fu_600_p3) < $signed(p_read10_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln43_10_fu_1180_p2 = (($signed(select_ln44_3_fu_1162_p3) < $signed(select_ln43_4_fu_1174_p3)) ? 1'b1 : 1'b0);

assign icmp_ln43_11_fu_1228_p2 = (($signed(select_ln44_5_fu_1210_p3) < $signed(select_ln43_6_fu_1222_p3)) ? 1'b1 : 1'b0);

assign icmp_ln43_12_fu_1452_p2 = (($signed(select_ln44_7_fu_1436_p3) < $signed(select_ln43_8_fu_1446_p3)) ? 1'b1 : 1'b0);

assign icmp_ln43_13_fu_1500_p2 = (($signed(select_ln44_9_fu_1482_p3) < $signed(select_ln43_10_fu_1494_p3)) ? 1'b1 : 1'b0);

assign icmp_ln43_14_fu_1643_p2 = (($signed(select_ln44_11_reg_2060) < $signed(select_ln43_12_reg_2066)) ? 1'b1 : 1'b0);

assign icmp_ln43_15_fu_1675_p2 = (($signed(select_ln44_13_fu_1658_p3) < $signed(select_ln43_14_fu_1669_p3)) ? 1'b1 : 1'b0);

assign icmp_ln43_1_fu_908_p2 = (($signed(select_ln43_fu_900_p3) > $signed(b0_fu_888_p2)) ? 1'b1 : 1'b0);

assign icmp_ln43_2_fu_1170_p2 = (($signed(select_ln28_2_reg_1879) > $signed(p_read511_reg_1827)) ? 1'b1 : 1'b0);

assign icmp_ln43_3_fu_1218_p2 = (($signed(select_ln28_3_reg_1895) > $signed(p_read713_reg_1811)) ? 1'b1 : 1'b0);

assign icmp_ln43_4_fu_1442_p2 = (($signed(select_ln28_4_reg_1911_pp0_iter1_reg) > $signed(p_read_14_reg_1795_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln43_5_fu_1490_p2 = (($signed(select_ln28_5_reg_1927_pp0_iter1_reg) > $signed(p_read_12_reg_1787_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln43_6_fu_1538_p2 = (($signed(select_ln28_6_reg_1943_pp0_iter1_reg) > $signed(p_read_10_reg_1771_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln43_7_fu_1665_p2 = (($signed(select_ln28_7_reg_1959_pp0_iter2_reg) > $signed(p_read_8_reg_1755_pp0_iter2_reg)) ? 1'b1 : 1'b0);

assign icmp_ln43_8_fu_942_p2 = (($signed(select_ln28_1_fu_642_p3) > $signed(p_read3_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln43_9_fu_1132_p2 = (($signed(select_ln44_1_fu_1122_p3) < $signed(select_ln43_2_fu_1127_p3)) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_894_p2 = (($signed(select_ln28_fu_614_p3) > $signed(p_read1_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln44_10_fu_1204_p2 = (($signed(select_ln43_5_fu_1186_p3) < $signed(select_ln44_4_fu_1198_p3)) ? 1'b1 : 1'b0);

assign icmp_ln44_11_fu_1432_p2 = (($signed(select_ln43_7_reg_2023) < $signed(select_ln44_6_reg_2029)) ? 1'b1 : 1'b0);

assign icmp_ln44_12_fu_1476_p2 = (($signed(select_ln43_9_fu_1458_p3) < $signed(select_ln44_8_fu_1470_p3)) ? 1'b1 : 1'b0);

assign icmp_ln44_13_fu_1524_p2 = (($signed(select_ln43_11_fu_1506_p3) < $signed(select_ln44_10_fu_1518_p3)) ? 1'b1 : 1'b0);

assign icmp_ln44_14_fu_1653_p2 = (($signed(select_ln43_13_fu_1647_p3) < $signed(select_ln44_12_reg_2072)) ? 1'b1 : 1'b0);

assign icmp_ln44_15_fu_1699_p2 = (($signed(select_ln43_15_fu_1681_p3) < $signed(select_ln44_14_fu_1693_p3)) ? 1'b1 : 1'b0);

assign icmp_ln44_1_fu_1146_p2 = (($signed(select_ln28_1_reg_1864) > $signed(p_read_11_reg_1779)) ? 1'b1 : 1'b0);

assign icmp_ln44_2_fu_936_p2 = (($signed(select_ln43_1_fu_914_p3) < $signed(select_ln44_fu_928_p3)) ? 1'b1 : 1'b0);

assign icmp_ln44_3_fu_1242_p2 = (($signed(select_ln28_3_reg_1895) > $signed(p_read_reg_1747)) ? 1'b1 : 1'b0);

assign icmp_ln44_4_fu_1466_p2 = (($signed(select_ln28_4_reg_1911_pp0_iter1_reg) > $signed(p_read28_reg_1849_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln44_5_fu_1514_p2 = (($signed(select_ln28_5_reg_1927_pp0_iter1_reg) > $signed(p_read410_reg_1835_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln44_6_fu_1548_p2 = (($signed(select_ln28_6_reg_1943_pp0_iter1_reg) > $signed(p_read612_reg_1819_pp0_iter1_reg)) ? 1'b1 : 1'b0);

assign icmp_ln44_7_fu_1689_p2 = (($signed(select_ln28_7_reg_1959_pp0_iter2_reg) > $signed(p_read814_reg_1803_pp0_iter2_reg)) ? 1'b1 : 1'b0);

assign icmp_ln44_8_fu_1156_p2 = (($signed(select_ln43_3_fu_1138_p3) < $signed(select_ln44_2_fu_1150_p3)) ? 1'b1 : 1'b0);

assign icmp_ln44_9_fu_1194_p2 = (($signed(select_ln28_2_reg_1879) > $signed(p_read_9_reg_1763)) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_922_p2 = (($signed(select_ln28_fu_614_p3) > $signed(p_read10_int_reg)) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_1727_p2 = ((select_ln37_15_fu_1635_p3 > sub_ln46_fu_1721_p2) ? 1'b1 : 1'b0);

assign score_V_fu_1741_p2 = ($signed(select_ln46_fu_1733_p3) + $signed(8'd255));

assign select_ln17_1_fu_180_p3 = ((icmp_ln17_1_fu_174_p2[0:0] == 1'b1) ? p_read4_int_reg : p_read5_int_reg);

assign select_ln17_2_fu_208_p3 = ((icmp_ln17_2_fu_202_p2[0:0] == 1'b1) ? p_read6_int_reg : p_read7_int_reg);

assign select_ln17_3_fu_236_p3 = ((icmp_ln17_3_fu_230_p2[0:0] == 1'b1) ? p_read8_int_reg : p_read9_int_reg);

assign select_ln17_4_fu_264_p3 = ((icmp_ln17_4_fu_258_p2[0:0] == 1'b1) ? p_read10_int_reg : p_read11_int_reg);

assign select_ln17_5_fu_292_p3 = ((icmp_ln17_5_fu_286_p2[0:0] == 1'b1) ? p_read12_int_reg : p_read13_int_reg);

assign select_ln17_6_fu_320_p3 = ((icmp_ln17_6_fu_314_p2[0:0] == 1'b1) ? p_read14_int_reg : p_read15_int_reg);

assign select_ln17_7_fu_348_p3 = ((icmp_ln17_7_fu_342_p2[0:0] == 1'b1) ? p_read16_int_reg : p_read1_int_reg);

assign select_ln17_fu_152_p3 = ((icmp_ln17_fu_146_p2[0:0] == 1'b1) ? p_read2_int_reg : p_read3_int_reg);

assign select_ln18_1_fu_194_p3 = ((icmp_ln18_1_fu_188_p2[0:0] == 1'b1) ? p_read4_int_reg : p_read5_int_reg);

assign select_ln18_2_fu_222_p3 = ((icmp_ln18_2_fu_216_p2[0:0] == 1'b1) ? p_read6_int_reg : p_read7_int_reg);

assign select_ln18_3_fu_250_p3 = ((icmp_ln18_3_fu_244_p2[0:0] == 1'b1) ? p_read8_int_reg : p_read9_int_reg);

assign select_ln18_4_fu_278_p3 = ((icmp_ln18_4_fu_272_p2[0:0] == 1'b1) ? p_read10_int_reg : p_read11_int_reg);

assign select_ln18_5_fu_306_p3 = ((icmp_ln18_5_fu_300_p2[0:0] == 1'b1) ? p_read12_int_reg : p_read13_int_reg);

assign select_ln18_6_fu_334_p3 = ((icmp_ln18_6_fu_328_p2[0:0] == 1'b1) ? p_read14_int_reg : p_read15_int_reg);

assign select_ln18_7_fu_362_p3 = ((icmp_ln18_7_fu_356_p2[0:0] == 1'b1) ? p_read16_int_reg : p_read1_int_reg);

assign select_ln18_fu_166_p3 = ((icmp_ln18_fu_160_p2[0:0] == 1'b1) ? p_read2_int_reg : p_read3_int_reg);

assign select_ln22_1_fu_404_p3 = ((icmp_ln22_1_fu_398_p2[0:0] == 1'b1) ? select_ln17_1_fu_180_p3 : select_ln17_2_fu_208_p3);

assign select_ln22_2_fu_432_p3 = ((icmp_ln22_2_fu_426_p2[0:0] == 1'b1) ? select_ln17_2_fu_208_p3 : select_ln17_3_fu_236_p3);

assign select_ln22_3_fu_460_p3 = ((icmp_ln22_3_fu_454_p2[0:0] == 1'b1) ? select_ln17_3_fu_236_p3 : select_ln17_4_fu_264_p3);

assign select_ln22_4_fu_488_p3 = ((icmp_ln22_4_fu_482_p2[0:0] == 1'b1) ? select_ln17_4_fu_264_p3 : select_ln17_5_fu_292_p3);

assign select_ln22_5_fu_516_p3 = ((icmp_ln22_5_fu_510_p2[0:0] == 1'b1) ? select_ln17_5_fu_292_p3 : select_ln17_6_fu_320_p3);

assign select_ln22_6_fu_544_p3 = ((icmp_ln22_6_fu_538_p2[0:0] == 1'b1) ? select_ln17_6_fu_320_p3 : select_ln17_7_fu_348_p3);

assign select_ln22_7_fu_572_p3 = ((icmp_ln22_7_fu_566_p2[0:0] == 1'b1) ? select_ln17_7_fu_348_p3 : select_ln17_fu_152_p3);

assign select_ln22_fu_376_p3 = ((icmp_ln22_fu_370_p2[0:0] == 1'b1) ? select_ln17_fu_152_p3 : select_ln17_1_fu_180_p3);

assign select_ln23_1_fu_418_p3 = ((icmp_ln23_1_fu_412_p2[0:0] == 1'b1) ? select_ln18_1_fu_194_p3 : select_ln18_2_fu_222_p3);

assign select_ln23_2_fu_446_p3 = ((icmp_ln23_2_fu_440_p2[0:0] == 1'b1) ? select_ln18_2_fu_222_p3 : select_ln18_3_fu_250_p3);

assign select_ln23_3_fu_474_p3 = ((icmp_ln23_3_fu_468_p2[0:0] == 1'b1) ? select_ln18_3_fu_250_p3 : select_ln18_4_fu_278_p3);

assign select_ln23_4_fu_502_p3 = ((icmp_ln23_4_fu_496_p2[0:0] == 1'b1) ? select_ln18_4_fu_278_p3 : select_ln18_5_fu_306_p3);

assign select_ln23_5_fu_530_p3 = ((icmp_ln23_5_fu_524_p2[0:0] == 1'b1) ? select_ln18_5_fu_306_p3 : select_ln18_6_fu_334_p3);

assign select_ln23_6_fu_558_p3 = ((icmp_ln23_6_fu_552_p2[0:0] == 1'b1) ? select_ln18_6_fu_334_p3 : select_ln18_7_fu_362_p3);

assign select_ln23_7_fu_586_p3 = ((icmp_ln23_7_fu_580_p2[0:0] == 1'b1) ? select_ln18_7_fu_362_p3 : select_ln18_fu_166_p3);

assign select_ln23_fu_390_p3 = ((icmp_ln23_fu_384_p2[0:0] == 1'b1) ? select_ln18_fu_166_p3 : select_ln18_1_fu_194_p3);

assign select_ln27_1_fu_628_p3 = ((icmp_ln27_1_fu_622_p2[0:0] == 1'b1) ? select_ln22_1_fu_404_p3 : select_ln22_3_fu_460_p3);

assign select_ln27_2_fu_656_p3 = ((icmp_ln27_2_fu_650_p2[0:0] == 1'b1) ? select_ln22_2_fu_432_p3 : select_ln22_4_fu_488_p3);

assign select_ln27_3_fu_684_p3 = ((icmp_ln27_3_fu_678_p2[0:0] == 1'b1) ? select_ln22_3_fu_460_p3 : select_ln22_5_fu_516_p3);

assign select_ln27_4_fu_712_p3 = ((icmp_ln27_4_fu_706_p2[0:0] == 1'b1) ? select_ln22_4_fu_488_p3 : select_ln22_6_fu_544_p3);

assign select_ln27_5_fu_740_p3 = ((icmp_ln27_5_fu_734_p2[0:0] == 1'b1) ? select_ln22_5_fu_516_p3 : select_ln22_7_fu_572_p3);

assign select_ln27_6_fu_768_p3 = ((icmp_ln27_6_fu_762_p2[0:0] == 1'b1) ? select_ln22_6_fu_544_p3 : select_ln22_fu_376_p3);

assign select_ln27_7_fu_796_p3 = ((icmp_ln27_7_fu_790_p2[0:0] == 1'b1) ? select_ln22_7_fu_572_p3 : select_ln22_1_fu_404_p3);

assign select_ln27_fu_600_p3 = ((icmp_ln27_fu_594_p2[0:0] == 1'b1) ? select_ln22_fu_376_p3 : select_ln22_2_fu_432_p3);

assign select_ln28_1_fu_642_p3 = ((icmp_ln28_1_fu_636_p2[0:0] == 1'b1) ? select_ln23_1_fu_418_p3 : select_ln23_3_fu_474_p3);

assign select_ln28_2_fu_670_p3 = ((icmp_ln28_2_fu_664_p2[0:0] == 1'b1) ? select_ln23_2_fu_446_p3 : select_ln23_4_fu_502_p3);

assign select_ln28_3_fu_698_p3 = ((icmp_ln28_3_fu_692_p2[0:0] == 1'b1) ? select_ln23_3_fu_474_p3 : select_ln23_5_fu_530_p3);

assign select_ln28_4_fu_726_p3 = ((icmp_ln28_4_fu_720_p2[0:0] == 1'b1) ? select_ln23_4_fu_502_p3 : select_ln23_6_fu_558_p3);

assign select_ln28_5_fu_754_p3 = ((icmp_ln28_5_fu_748_p2[0:0] == 1'b1) ? select_ln23_5_fu_530_p3 : select_ln23_7_fu_586_p3);

assign select_ln28_6_fu_782_p3 = ((icmp_ln28_6_fu_776_p2[0:0] == 1'b1) ? select_ln23_6_fu_558_p3 : select_ln23_fu_390_p3);

assign select_ln28_7_fu_810_p3 = ((icmp_ln28_7_fu_804_p2[0:0] == 1'b1) ? select_ln23_7_fu_586_p3 : select_ln23_1_fu_418_p3);

assign select_ln28_fu_614_p3 = ((icmp_ln28_fu_608_p2[0:0] == 1'b1) ? select_ln23_fu_390_p3 : select_ln23_2_fu_446_p3);

assign select_ln36_10_fu_1036_p3 = ((icmp_ln36_10_fu_1026_p2[0:0] == 1'b1) ? select_ln37_9_fu_1004_p3 : trunc_ln36_2_fu_1032_p1);

assign select_ln36_11_fu_1100_p3 = ((icmp_ln36_11_fu_1090_p2[0:0] == 1'b1) ? select_ln37_10_fu_1068_p3 : trunc_ln36_3_fu_1096_p1);

assign select_ln36_12_fu_1290_p3 = ((icmp_ln36_12_fu_1280_p2[0:0] == 1'b1) ? select_ln37_11_fu_1260_p3 : trunc_ln36_4_fu_1286_p1);

assign select_ln36_13_fu_1354_p3 = ((icmp_ln36_13_fu_1344_p2[0:0] == 1'b1) ? select_ln37_12_fu_1322_p3 : trunc_ln36_5_fu_1350_p1);

assign select_ln36_14_fu_1558_p3 = ((icmp_ln36_14_reg_2040[0:0] == 1'b1) ? select_ln37_13_reg_2035 : trunc_ln36_6_reg_2045);

assign select_ln36_15_fu_1603_p3 = ((icmp_ln36_15_fu_1593_p2[0:0] == 1'b1) ? select_ln37_14_fu_1572_p3 : trunc_ln36_7_fu_1599_p1);

assign select_ln36_1_fu_957_p3 = ((icmp_ln36_8_reg_1982[0:0] == 1'b1) ? select_ln27_1_reg_1857 : p_read39_reg_1843);

assign select_ln36_2_fu_1020_p3 = ((icmp_ln36_2_fu_1016_p2[0:0] == 1'b1) ? select_ln27_2_reg_1871 : p_read511_reg_1827);

assign select_ln36_3_fu_1084_p3 = ((icmp_ln36_3_fu_1080_p2[0:0] == 1'b1) ? select_ln27_3_reg_1887 : p_read713_reg_1811);

assign select_ln36_4_fu_1274_p3 = ((icmp_ln36_4_fu_1270_p2[0:0] == 1'b1) ? select_ln27_4_reg_1903_pp0_iter1_reg : p_read_14_reg_1795_pp0_iter1_reg);

assign select_ln36_5_fu_1338_p3 = ((icmp_ln36_5_fu_1334_p2[0:0] == 1'b1) ? select_ln27_5_reg_1919_pp0_iter1_reg : p_read_12_reg_1787_pp0_iter1_reg);

assign select_ln36_6_fu_1402_p3 = ((icmp_ln36_6_fu_1398_p2[0:0] == 1'b1) ? select_ln27_6_reg_1935_pp0_iter1_reg : p_read_10_reg_1771_pp0_iter1_reg);

assign select_ln36_7_fu_1587_p3 = ((icmp_ln36_7_fu_1583_p2[0:0] == 1'b1) ? select_ln27_7_reg_1951_pp0_iter2_reg : p_read_8_reg_1755_pp0_iter2_reg);

assign select_ln36_8_fu_846_p3 = ((icmp_ln36_1_fu_836_p2[0:0] == 1'b1) ? p_threshold_int_reg : trunc_ln36_fu_842_p1);

assign select_ln36_9_fu_972_p3 = ((icmp_ln36_9_fu_962_p2[0:0] == 1'b1) ? select_ln37_1_fu_948_p3 : trunc_ln36_1_fu_968_p1);

assign select_ln36_fu_828_p3 = ((icmp_ln36_fu_822_p2[0:0] == 1'b1) ? select_ln27_fu_600_p3 : p_read1_int_reg);

assign select_ln37_10_fu_1068_p3 = ((icmp_ln37_10_fu_1058_p2[0:0] == 1'b1) ? select_ln36_10_fu_1036_p3 : trunc_ln37_2_fu_1064_p1);

assign select_ln37_11_fu_1260_p3 = ((icmp_ln37_11_fu_1255_p2[0:0] == 1'b1) ? select_ln36_11_reg_2007 : trunc_ln37_3_reg_2018);

assign select_ln37_12_fu_1322_p3 = ((icmp_ln37_12_fu_1312_p2[0:0] == 1'b1) ? select_ln36_12_fu_1290_p3 : trunc_ln37_4_fu_1318_p1);

assign select_ln37_13_fu_1386_p3 = ((icmp_ln37_13_fu_1376_p2[0:0] == 1'b1) ? select_ln36_13_fu_1354_p3 : trunc_ln37_5_fu_1382_p1);

assign select_ln37_14_fu_1572_p3 = ((icmp_ln37_14_fu_1567_p2[0:0] == 1'b1) ? select_ln36_14_fu_1558_p3 : trunc_ln37_6_reg_2055);

assign select_ln37_15_fu_1635_p3 = ((icmp_ln37_15_fu_1625_p2[0:0] == 1'b1) ? select_ln36_15_fu_1603_p3 : trunc_ln37_7_fu_1631_p1);

assign select_ln37_1_fu_948_p3 = ((icmp_ln37_1_reg_1972[0:0] == 1'b1) ? select_ln36_8_reg_1967 : trunc_ln37_reg_1977);

assign select_ln37_2_fu_1052_p3 = ((icmp_ln37_2_fu_1048_p2[0:0] == 1'b1) ? select_ln27_2_reg_1871 : p_read_9_reg_1763);

assign select_ln37_3_fu_1112_p3 = ((icmp_ln37_3_fu_1108_p2[0:0] == 1'b1) ? select_ln27_3_reg_1887 : p_read_reg_1747);

assign select_ln37_4_fu_1306_p3 = ((icmp_ln37_4_fu_1302_p2[0:0] == 1'b1) ? select_ln27_4_reg_1903_pp0_iter1_reg : p_read28_reg_1849_pp0_iter1_reg);

assign select_ln37_5_fu_1370_p3 = ((icmp_ln37_5_fu_1366_p2[0:0] == 1'b1) ? select_ln27_5_reg_1919_pp0_iter1_reg : p_read410_reg_1835_pp0_iter1_reg);

assign select_ln37_6_fu_1422_p3 = ((icmp_ln37_6_fu_1418_p2[0:0] == 1'b1) ? select_ln27_6_reg_1935_pp0_iter1_reg : p_read612_reg_1819_pp0_iter1_reg);

assign select_ln37_7_fu_1619_p3 = ((icmp_ln37_7_fu_1615_p2[0:0] == 1'b1) ? select_ln27_7_reg_1951_pp0_iter2_reg : p_read814_reg_1803_pp0_iter2_reg);

assign select_ln37_8_fu_988_p3 = ((icmp_ln37_8_fu_984_p2[0:0] == 1'b1) ? select_ln27_1_reg_1857 : p_read_11_reg_1779);

assign select_ln37_9_fu_1004_p3 = ((icmp_ln37_9_fu_994_p2[0:0] == 1'b1) ? select_ln36_9_fu_972_p3 : trunc_ln37_1_fu_1000_p1);

assign select_ln37_fu_864_p3 = ((icmp_ln37_fu_858_p2[0:0] == 1'b1) ? select_ln27_fu_600_p3 : p_read10_int_reg);

assign select_ln43_10_fu_1494_p3 = ((icmp_ln43_5_fu_1490_p2[0:0] == 1'b1) ? select_ln28_5_reg_1927_pp0_iter1_reg : p_read_12_reg_1787_pp0_iter1_reg);

assign select_ln43_11_fu_1506_p3 = ((icmp_ln43_13_fu_1500_p2[0:0] == 1'b1) ? select_ln44_9_fu_1482_p3 : select_ln43_10_fu_1494_p3);

assign select_ln43_12_fu_1542_p3 = ((icmp_ln43_6_fu_1538_p2[0:0] == 1'b1) ? select_ln28_6_reg_1943_pp0_iter1_reg : p_read_10_reg_1771_pp0_iter1_reg);

assign select_ln43_13_fu_1647_p3 = ((icmp_ln43_14_fu_1643_p2[0:0] == 1'b1) ? select_ln44_11_reg_2060 : select_ln43_12_reg_2066);

assign select_ln43_14_fu_1669_p3 = ((icmp_ln43_7_fu_1665_p2[0:0] == 1'b1) ? select_ln28_7_reg_1959_pp0_iter2_reg : p_read_8_reg_1755_pp0_iter2_reg);

assign select_ln43_15_fu_1681_p3 = ((icmp_ln43_15_fu_1675_p2[0:0] == 1'b1) ? select_ln44_13_fu_1658_p3 : select_ln43_14_fu_1669_p3);

assign select_ln43_1_fu_914_p3 = ((icmp_ln43_1_fu_908_p2[0:0] == 1'b1) ? b0_fu_888_p2 : select_ln43_fu_900_p3);

assign select_ln43_2_fu_1127_p3 = ((icmp_ln43_8_reg_2002[0:0] == 1'b1) ? select_ln28_1_reg_1864 : p_read39_reg_1843);

assign select_ln43_3_fu_1138_p3 = ((icmp_ln43_9_fu_1132_p2[0:0] == 1'b1) ? select_ln44_1_fu_1122_p3 : select_ln43_2_fu_1127_p3);

assign select_ln43_4_fu_1174_p3 = ((icmp_ln43_2_fu_1170_p2[0:0] == 1'b1) ? select_ln28_2_reg_1879 : p_read511_reg_1827);

assign select_ln43_5_fu_1186_p3 = ((icmp_ln43_10_fu_1180_p2[0:0] == 1'b1) ? select_ln44_3_fu_1162_p3 : select_ln43_4_fu_1174_p3);

assign select_ln43_6_fu_1222_p3 = ((icmp_ln43_3_fu_1218_p2[0:0] == 1'b1) ? select_ln28_3_reg_1895 : p_read713_reg_1811);

assign select_ln43_7_fu_1234_p3 = ((icmp_ln43_11_fu_1228_p2[0:0] == 1'b1) ? select_ln44_5_fu_1210_p3 : select_ln43_6_fu_1222_p3);

assign select_ln43_8_fu_1446_p3 = ((icmp_ln43_4_fu_1442_p2[0:0] == 1'b1) ? select_ln28_4_reg_1911_pp0_iter1_reg : p_read_14_reg_1795_pp0_iter1_reg);

assign select_ln43_9_fu_1458_p3 = ((icmp_ln43_12_fu_1452_p2[0:0] == 1'b1) ? select_ln44_7_fu_1436_p3 : select_ln43_8_fu_1446_p3);

assign select_ln43_fu_900_p3 = ((icmp_ln43_fu_894_p2[0:0] == 1'b1) ? select_ln28_fu_614_p3 : p_read1_int_reg);

assign select_ln44_10_fu_1518_p3 = ((icmp_ln44_5_fu_1514_p2[0:0] == 1'b1) ? select_ln28_5_reg_1927_pp0_iter1_reg : p_read410_reg_1835_pp0_iter1_reg);

assign select_ln44_11_fu_1530_p3 = ((icmp_ln44_13_fu_1524_p2[0:0] == 1'b1) ? select_ln43_11_fu_1506_p3 : select_ln44_10_fu_1518_p3);

assign select_ln44_12_fu_1552_p3 = ((icmp_ln44_6_fu_1548_p2[0:0] == 1'b1) ? select_ln28_6_reg_1943_pp0_iter1_reg : p_read612_reg_1819_pp0_iter1_reg);

assign select_ln44_13_fu_1658_p3 = ((icmp_ln44_14_fu_1653_p2[0:0] == 1'b1) ? select_ln43_13_fu_1647_p3 : select_ln44_12_reg_2072);

assign select_ln44_14_fu_1693_p3 = ((icmp_ln44_7_fu_1689_p2[0:0] == 1'b1) ? select_ln28_7_reg_1959_pp0_iter2_reg : p_read814_reg_1803_pp0_iter2_reg);

assign select_ln44_15_fu_1713_p3 = ((icmp_ln44_15_fu_1699_p2[0:0] == 1'b1) ? trunc_ln44_fu_1705_p1 : trunc_ln44_1_fu_1709_p1);

assign select_ln44_1_fu_1122_p3 = ((icmp_ln44_2_reg_1997[0:0] == 1'b1) ? select_ln43_1_reg_1987 : select_ln44_reg_1992);

assign select_ln44_2_fu_1150_p3 = ((icmp_ln44_1_fu_1146_p2[0:0] == 1'b1) ? select_ln28_1_reg_1864 : p_read_11_reg_1779);

assign select_ln44_3_fu_1162_p3 = ((icmp_ln44_8_fu_1156_p2[0:0] == 1'b1) ? select_ln43_3_fu_1138_p3 : select_ln44_2_fu_1150_p3);

assign select_ln44_4_fu_1198_p3 = ((icmp_ln44_9_fu_1194_p2[0:0] == 1'b1) ? select_ln28_2_reg_1879 : p_read_9_reg_1763);

assign select_ln44_5_fu_1210_p3 = ((icmp_ln44_10_fu_1204_p2[0:0] == 1'b1) ? select_ln43_5_fu_1186_p3 : select_ln44_4_fu_1198_p3);

assign select_ln44_6_fu_1246_p3 = ((icmp_ln44_3_fu_1242_p2[0:0] == 1'b1) ? select_ln28_3_reg_1895 : p_read_reg_1747);

assign select_ln44_7_fu_1436_p3 = ((icmp_ln44_11_fu_1432_p2[0:0] == 1'b1) ? select_ln43_7_reg_2023 : select_ln44_6_reg_2029);

assign select_ln44_8_fu_1470_p3 = ((icmp_ln44_4_fu_1466_p2[0:0] == 1'b1) ? select_ln28_4_reg_1911_pp0_iter1_reg : p_read28_reg_1849_pp0_iter1_reg);

assign select_ln44_9_fu_1482_p3 = ((icmp_ln44_12_fu_1476_p2[0:0] == 1'b1) ? select_ln43_9_fu_1458_p3 : select_ln44_8_fu_1470_p3);

assign select_ln44_fu_928_p3 = ((icmp_ln44_fu_922_p2[0:0] == 1'b1) ? select_ln28_fu_614_p3 : p_read10_int_reg);

assign select_ln46_fu_1733_p3 = ((icmp_ln46_fu_1727_p2[0:0] == 1'b1) ? select_ln37_15_fu_1635_p3 : sub_ln46_fu_1721_p2);

assign sub_ln46_fu_1721_p2 = (8'd0 - select_ln44_15_fu_1713_p3);

assign trunc_ln36_1_fu_968_p1 = select_ln36_1_fu_957_p3[7:0];

assign trunc_ln36_2_fu_1032_p1 = select_ln36_2_fu_1020_p3[7:0];

assign trunc_ln36_3_fu_1096_p1 = select_ln36_3_fu_1084_p3[7:0];

assign trunc_ln36_4_fu_1286_p1 = select_ln36_4_fu_1274_p3[7:0];

assign trunc_ln36_5_fu_1350_p1 = select_ln36_5_fu_1338_p3[7:0];

assign trunc_ln36_6_fu_1414_p1 = select_ln36_6_fu_1402_p3[7:0];

assign trunc_ln36_7_fu_1599_p1 = select_ln36_7_fu_1587_p3[7:0];

assign trunc_ln36_fu_842_p1 = select_ln36_fu_828_p3[7:0];

assign trunc_ln37_1_fu_1000_p1 = select_ln37_8_fu_988_p3[7:0];

assign trunc_ln37_2_fu_1064_p1 = select_ln37_2_fu_1052_p3[7:0];

assign trunc_ln37_3_fu_1118_p1 = select_ln37_3_fu_1112_p3[7:0];

assign trunc_ln37_4_fu_1318_p1 = select_ln37_4_fu_1306_p3[7:0];

assign trunc_ln37_5_fu_1382_p1 = select_ln37_5_fu_1370_p3[7:0];

assign trunc_ln37_6_fu_1428_p1 = select_ln37_6_fu_1422_p3[7:0];

assign trunc_ln37_7_fu_1631_p1 = select_ln37_7_fu_1619_p3[7:0];

assign trunc_ln37_fu_878_p1 = select_ln37_fu_864_p3[7:0];

assign trunc_ln44_1_fu_1709_p1 = select_ln44_14_fu_1693_p3[7:0];

assign trunc_ln44_fu_1705_p1 = select_ln43_15_fu_1681_p3[7:0];

assign zext_ln36_1_fu_953_p1 = select_ln37_1_fu_948_p3;

assign zext_ln36_2_fu_1012_p1 = select_ln37_9_fu_1004_p3;

assign zext_ln36_3_fu_1076_p1 = select_ln37_10_fu_1068_p3;

assign zext_ln36_4_fu_1266_p1 = select_ln37_11_fu_1260_p3;

assign zext_ln36_5_fu_1330_p1 = select_ln37_12_fu_1322_p3;

assign zext_ln36_6_fu_1394_p1 = select_ln37_13_fu_1386_p3;

assign zext_ln36_7_fu_1579_p1 = select_ln37_14_fu_1572_p3;

assign zext_ln36_fu_818_p1 = p_threshold_int_reg;

assign zext_ln37_1_fu_980_p1 = select_ln36_9_fu_972_p3;

assign zext_ln37_2_fu_1044_p1 = select_ln36_10_fu_1036_p3;

assign zext_ln37_3_fu_1252_p1 = select_ln36_11_reg_2007;

assign zext_ln37_4_fu_1298_p1 = select_ln36_12_fu_1290_p3;

assign zext_ln37_5_fu_1362_p1 = select_ln36_13_fu_1354_p3;

assign zext_ln37_6_fu_1563_p1 = select_ln36_14_fu_1558_p3;

assign zext_ln37_7_fu_1611_p1 = select_ln36_15_fu_1603_p3;

assign zext_ln37_fu_854_p1 = select_ln36_8_fu_846_p3;

endmodule //ORB_accel_fast_score
