// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ORB_accel_round_fixed_16_9_s (
        ap_ready,
        x,
        ap_return
);


output   ap_ready;
input  [13:0] x;
output  [15:0] ap_return;

wire  signed [13:0] sext_ln201_fu_40_p0;
wire  signed [13:0] p_Val2_s_fu_44_p1;
wire   [13:0] p_Val2_s_fu_44_p2;
wire  signed [15:0] sext_ln104_fu_50_p1;
wire  signed [13:0] p_Result_s_fu_64_p1;
wire   [0:0] p_Result_s_fu_64_p3;
wire   [15:0] p_Result_2_fu_54_p4;
wire  signed [15:0] sext_ln201_fu_40_p1;
wire   [15:0] x_pos_fu_72_p3;
wire   [16:0] zext_ln703_fu_80_p1;
wire   [16:0] ret_V_fu_84_p2;
wire   [16:0] p_Result_3_fu_90_p5;
wire   [15:0] trunc_ln703_fu_102_p1;
wire   [15:0] sub_ln703_fu_106_p2;

assign ap_ready = 1'b1;

assign ap_return = ((p_Result_s_fu_64_p3[0:0] == 1'b1) ? sub_ln703_fu_106_p2 : trunc_ln703_fu_102_p1);

assign p_Result_2_fu_54_p4 = {|(1'd0), sext_ln104_fu_50_p1[15 - 1:0]};

assign p_Result_3_fu_90_p5 = {{ret_V_fu_84_p2[16:7]}, {7'd0}};

assign p_Result_s_fu_64_p1 = x;

assign p_Result_s_fu_64_p3 = p_Result_s_fu_64_p1[32'd13];

assign p_Val2_s_fu_44_p1 = x;

assign p_Val2_s_fu_44_p2 = ($signed(14'd0) - $signed(p_Val2_s_fu_44_p1));

assign ret_V_fu_84_p2 = (zext_ln703_fu_80_p1 + 17'd64);

assign sext_ln104_fu_50_p1 = $signed(p_Val2_s_fu_44_p2);

assign sext_ln201_fu_40_p0 = x;

assign sext_ln201_fu_40_p1 = sext_ln201_fu_40_p0;

assign sub_ln703_fu_106_p2 = (16'd0 - trunc_ln703_fu_102_p1);

assign trunc_ln703_fu_102_p1 = p_Result_3_fu_90_p5[15:0];

assign x_pos_fu_72_p3 = ((p_Result_s_fu_64_p3[0:0] == 1'b1) ? p_Result_2_fu_54_p4 : sext_ln201_fu_40_p1);

assign zext_ln703_fu_80_p1 = x_pos_fu_72_p3;

endmodule //ORB_accel_round_fixed_16_9_s
