// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ORB_accel_process_ORB_8_0_1080_1920_1_entry336 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        height,
        width,
        height_new,
        width_new,
        threshold,
        height_out_din,
        height_out_full_n,
        height_out_write,
        height_out1_din,
        height_out1_full_n,
        height_out1_write,
        width_out_din,
        width_out_full_n,
        width_out_write,
        width_out2_din,
        width_out2_full_n,
        width_out2_write,
        height_new_out_din,
        height_new_out_full_n,
        height_new_out_write,
        width_new_out_din,
        width_new_out_full_n,
        width_new_out_write,
        threshold_out_din,
        threshold_out_full_n,
        threshold_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [10:0] height;
input  [10:0] width;
input  [10:0] height_new;
input  [10:0] width_new;
input  [7:0] threshold;
output  [10:0] height_out_din;
input   height_out_full_n;
output   height_out_write;
output  [10:0] height_out1_din;
input   height_out1_full_n;
output   height_out1_write;
output  [10:0] width_out_din;
input   width_out_full_n;
output   width_out_write;
output  [10:0] width_out2_din;
input   width_out2_full_n;
output   width_out2_write;
output  [10:0] height_new_out_din;
input   height_new_out_full_n;
output   height_new_out_write;
output  [10:0] width_new_out_din;
input   width_new_out_full_n;
output   width_new_out_write;
output  [7:0] threshold_out_din;
input   threshold_out_full_n;
output   threshold_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg height_out_write;
reg height_out1_write;
reg width_out_write;
reg width_out2_write;
reg height_new_out_write;
reg width_new_out_write;
reg threshold_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    height_out_blk_n;
reg    height_out1_blk_n;
reg    width_out_blk_n;
reg    width_out2_blk_n;
reg    height_new_out_blk_n;
reg    width_new_out_blk_n;
reg    threshold_out_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (threshold_out_full_n == 1'b0) | (width_new_out_full_n == 1'b0) | (height_new_out_full_n == 1'b0) | (width_out2_full_n == 1'b0) | (width_out_full_n == 1'b0) | (height_out1_full_n == 1'b0) | (height_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (threshold_out_full_n == 1'b0) | (width_new_out_full_n == 1'b0) | (height_new_out_full_n == 1'b0) | (width_out2_full_n == 1'b0) | (width_out_full_n == 1'b0) | (height_out1_full_n == 1'b0) | (height_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_new_out_blk_n = height_new_out_full_n;
    end else begin
        height_new_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (threshold_out_full_n == 1'b0) | (width_new_out_full_n == 1'b0) | (height_new_out_full_n == 1'b0) | (width_out2_full_n == 1'b0) | (width_out_full_n == 1'b0) | (height_out1_full_n == 1'b0) | (height_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_new_out_write = 1'b1;
    end else begin
        height_new_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_out1_blk_n = height_out1_full_n;
    end else begin
        height_out1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (threshold_out_full_n == 1'b0) | (width_new_out_full_n == 1'b0) | (height_new_out_full_n == 1'b0) | (width_out2_full_n == 1'b0) | (width_out_full_n == 1'b0) | (height_out1_full_n == 1'b0) | (height_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_out1_write = 1'b1;
    end else begin
        height_out1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_out_blk_n = height_out_full_n;
    end else begin
        height_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (threshold_out_full_n == 1'b0) | (width_new_out_full_n == 1'b0) | (height_new_out_full_n == 1'b0) | (width_out2_full_n == 1'b0) | (width_out_full_n == 1'b0) | (height_out1_full_n == 1'b0) | (height_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_out_write = 1'b1;
    end else begin
        height_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (threshold_out_full_n == 1'b0) | (width_new_out_full_n == 1'b0) | (height_new_out_full_n == 1'b0) | (width_out2_full_n == 1'b0) | (width_out_full_n == 1'b0) | (height_out1_full_n == 1'b0) | (height_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        threshold_out_blk_n = threshold_out_full_n;
    end else begin
        threshold_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (threshold_out_full_n == 1'b0) | (width_new_out_full_n == 1'b0) | (height_new_out_full_n == 1'b0) | (width_out2_full_n == 1'b0) | (width_out_full_n == 1'b0) | (height_out1_full_n == 1'b0) | (height_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        threshold_out_write = 1'b1;
    end else begin
        threshold_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_new_out_blk_n = width_new_out_full_n;
    end else begin
        width_new_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (threshold_out_full_n == 1'b0) | (width_new_out_full_n == 1'b0) | (height_new_out_full_n == 1'b0) | (width_out2_full_n == 1'b0) | (width_out_full_n == 1'b0) | (height_out1_full_n == 1'b0) | (height_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_new_out_write = 1'b1;
    end else begin
        width_new_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_out2_blk_n = width_out2_full_n;
    end else begin
        width_out2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (threshold_out_full_n == 1'b0) | (width_new_out_full_n == 1'b0) | (height_new_out_full_n == 1'b0) | (width_out2_full_n == 1'b0) | (width_out_full_n == 1'b0) | (height_out1_full_n == 1'b0) | (height_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_out2_write = 1'b1;
    end else begin
        width_out2_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_out_blk_n = width_out_full_n;
    end else begin
        width_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (threshold_out_full_n == 1'b0) | (width_new_out_full_n == 1'b0) | (height_new_out_full_n == 1'b0) | (width_out2_full_n == 1'b0) | (width_out_full_n == 1'b0) | (height_out1_full_n == 1'b0) | (height_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_out_write = 1'b1;
    end else begin
        width_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (threshold_out_full_n == 1'b0) | (width_new_out_full_n == 1'b0) | (height_new_out_full_n == 1'b0) | (width_out2_full_n == 1'b0) | (width_out_full_n == 1'b0) | (height_out1_full_n == 1'b0) | (height_out_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign height_new_out_din = height_new;

assign height_out1_din = height;

assign height_out_din = height;

assign start_out = real_start;

assign threshold_out_din = threshold;

assign width_new_out_din = width_new;

assign width_out2_din = width;

assign width_out_din = width;

endmodule //ORB_accel_process_ORB_8_0_1080_1920_1_entry336
