-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ORB_accel is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    src_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    src_TVALID : IN STD_LOGIC;
    src_TREADY : OUT STD_LOGIC;
    src_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    dst_TDATA : OUT STD_LOGIC_VECTOR (295 downto 0);
    dst_TVALID : OUT STD_LOGIC;
    dst_TREADY : IN STD_LOGIC;
    dst_TKEEP : OUT STD_LOGIC_VECTOR (36 downto 0);
    dst_TSTRB : OUT STD_LOGIC_VECTOR (36 downto 0);
    dst_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of ORB_accel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ORB_accel_ORB_accel,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.273750,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=208,HLS_SYN_DSP=0,HLS_SYN_FF=50255,HLS_SYN_LUT=42365,HLS_VERSION=2020_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv37_1FFFFFFFFF : STD_LOGIC_VECTOR (36 downto 0) := "1111111111111111111111111111111111111";
    constant ap_const_lv37_0 : STD_LOGIC_VECTOR (36 downto 0) := "0000000000000000000000000000000000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv15_64 : STD_LOGIC_VECTOR (14 downto 0) := "000000001100100";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal height : STD_LOGIC_VECTOR (31 downto 0);
    signal width : STD_LOGIC_VECTOR (31 downto 0);
    signal height_new : STD_LOGIC_VECTOR (31 downto 0);
    signal width_new : STD_LOGIC_VECTOR (31 downto 0);
    signal threshold : STD_LOGIC_VECTOR (31 downto 0);
    signal cntTree_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal cntTree_ce0 : STD_LOGIC;
    signal cntTree_we0 : STD_LOGIC;
    signal cntTree_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal cntTree_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal cntTree_ce1 : STD_LOGIC;
    signal cntTree_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal idxTree_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal idxTree_ce0 : STD_LOGIC;
    signal idxTree_we0 : STD_LOGIC;
    signal idxTree_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln353_reg_516 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln353_reg_516_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal i_reg_236 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_fu_302_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_reg_439 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal empty_405_fu_307_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_405_reg_444 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_406_fu_312_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_406_reg_449 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_407_fu_317_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_407_reg_454 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_408_fu_322_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_408_reg_459 : STD_LOGIC_VECTOR (10 downto 0);
    signal nFeatures_load_reg_464 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sub9_fu_330_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub9_reg_469 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln351_fu_336_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln351_reg_474 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal regslice_both_dst_V_data_V_U_apdone_blk : STD_LOGIC;
    signal empty_409_fu_352_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_409_reg_482 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln351_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cntTree_addr_reg_487 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln354_fu_366_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln354_reg_492 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal cntTree_load_reg_497 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln352_fu_372_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_state7_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state8_io : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state9_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln352_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln353_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_axi_last_V_fu_405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_axi_last_V_reg_520 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln301_fu_421_p1 : STD_LOGIC_VECTOR (295 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state7 : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDATA : STD_LOGIC_VECTOR (295 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TKEEP : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TSTRB : STD_LOGIC_VECTOR (36 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_length_r : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce0 : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_we0 : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce1 : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_we1 : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_ce0 : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_we0 : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_address1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_ce1 : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_we1 : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_src_TREADY : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TREADY : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_length_r_ap_vld : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_idle : STD_LOGIC;
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_continue : STD_LOGIC;
    signal val_reg_225 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready : STD_LOGIC;
    signal ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done : STD_LOGIC;
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done : STD_LOGIC := '0';
    signal nFeatures_fu_134 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_cast_fu_358_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln354_1_fu_395_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal cnt_fu_130 : STD_LOGIC_VECTOR (31 downto 0);
    signal cnt_9_fu_410_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln351_fu_348_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln354_fu_366_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln354_fu_366_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln354_fu_386_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln354_fu_390_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_src_V_data_V_U_apdone_blk : STD_LOGIC;
    signal src_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal src_TVALID_int_regslice : STD_LOGIC;
    signal src_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_src_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_src_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal src_TKEEP_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_src_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_src_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_src_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal src_TSTRB_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_src_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_src_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_src_V_user_V_U_apdone_blk : STD_LOGIC;
    signal src_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_src_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_src_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_src_V_last_V_U_apdone_blk : STD_LOGIC;
    signal src_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_src_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_src_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_src_V_id_V_U_apdone_blk : STD_LOGIC;
    signal src_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_src_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_src_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_src_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal src_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_src_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_src_V_dest_V_U_ack_in : STD_LOGIC;
    signal dst_TDATA_int_regslice : STD_LOGIC_VECTOR (295 downto 0);
    signal dst_TVALID_int_regslice : STD_LOGIC;
    signal dst_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_dst_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_dst_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal dst_TKEEP_int_regslice : STD_LOGIC_VECTOR (36 downto 0);
    signal regslice_both_dst_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_dst_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_dst_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal dst_TSTRB_int_regslice : STD_LOGIC_VECTOR (36 downto 0);
    signal regslice_both_dst_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_dst_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_dst_V_user_V_U_apdone_blk : STD_LOGIC;
    signal dst_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_dst_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_dst_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_dst_V_last_V_U_apdone_blk : STD_LOGIC;
    signal dst_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_dst_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_dst_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_dst_V_id_V_U_apdone_blk : STD_LOGIC;
    signal dst_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_dst_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_dst_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_dst_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal dst_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_dst_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_dst_V_dest_V_U_vld_out : STD_LOGIC;
    signal mul_ln354_fu_366_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal ap_return : STD_LOGIC_VECTOR (31 downto 0);

    component ORB_accel_process_ORB_8_0_1080_1920_1_s IS
    port (
        src_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        src_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
        src_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
        src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        dst_TDATA : OUT STD_LOGIC_VECTOR (295 downto 0);
        dst_TKEEP : OUT STD_LOGIC_VECTOR (36 downto 0);
        dst_TSTRB : OUT STD_LOGIC_VECTOR (36 downto 0);
        dst_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        dst_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        dst_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        dst_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
        height : IN STD_LOGIC_VECTOR (10 downto 0);
        width : IN STD_LOGIC_VECTOR (10 downto 0);
        height_new : IN STD_LOGIC_VECTOR (10 downto 0);
        width_new : IN STD_LOGIC_VECTOR (10 downto 0);
        threshold : IN STD_LOGIC_VECTOR (7 downto 0);
        length_r : OUT STD_LOGIC_VECTOR (31 downto 0);
        cntTree_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        cntTree_ce0 : OUT STD_LOGIC;
        cntTree_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        cntTree_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        cntTree_we0 : OUT STD_LOGIC;
        cntTree_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        cntTree_ce1 : OUT STD_LOGIC;
        cntTree_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        cntTree_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        cntTree_we1 : OUT STD_LOGIC;
        idxTree_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        idxTree_ce0 : OUT STD_LOGIC;
        idxTree_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        idxTree_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        idxTree_we0 : OUT STD_LOGIC;
        idxTree_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
        idxTree_ce1 : OUT STD_LOGIC;
        idxTree_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        idxTree_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        idxTree_we1 : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        height_ap_vld : IN STD_LOGIC;
        width_ap_vld : IN STD_LOGIC;
        height_new_ap_vld : IN STD_LOGIC;
        width_new_ap_vld : IN STD_LOGIC;
        threshold_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        src_TVALID : IN STD_LOGIC;
        src_TREADY : OUT STD_LOGIC;
        dst_TVALID : OUT STD_LOGIC;
        dst_TREADY : IN STD_LOGIC;
        length_r_ap_vld : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component ORB_accel_mul_8ns_8ns_15_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component ORB_accel_cntTree IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ORB_accel_idxTree IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ORB_accel_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_return : IN STD_LOGIC_VECTOR (31 downto 0);
        height : OUT STD_LOGIC_VECTOR (31 downto 0);
        width : OUT STD_LOGIC_VECTOR (31 downto 0);
        height_new : OUT STD_LOGIC_VECTOR (31 downto 0);
        width_new : OUT STD_LOGIC_VECTOR (31 downto 0);
        threshold : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ORB_accel_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    cntTree_U : component ORB_accel_cntTree
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => cntTree_address0,
        ce0 => cntTree_ce0,
        we0 => cntTree_we0,
        d0 => cntTree_d0,
        q0 => cntTree_q0,
        address1 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address1,
        ce1 => cntTree_ce1,
        q1 => cntTree_q1);

    idxTree_U : component ORB_accel_idxTree
    generic map (
        DataWidth => 32,
        AddressRange => 25600,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => idxTree_address0,
        ce0 => idxTree_ce0,
        we0 => idxTree_we0,
        d0 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_d0,
        q0 => idxTree_q0);

    control_s_axi_U : component ORB_accel_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        ap_return => nFeatures_fu_134,
        height => height,
        width => width,
        height_new => height_new,
        width_new => width_new,
        threshold => threshold);

    grp_process_ORB_8_0_1080_1920_1_s_fu_247 : component ORB_accel_process_ORB_8_0_1080_1920_1_s
    port map (
        src_TDATA => src_TDATA_int_regslice,
        src_TKEEP => src_TKEEP_int_regslice,
        src_TSTRB => src_TSTRB_int_regslice,
        src_TUSER => src_TUSER_int_regslice,
        src_TLAST => src_TLAST_int_regslice,
        src_TID => src_TID_int_regslice,
        src_TDEST => src_TDEST_int_regslice,
        dst_TDATA => grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDATA,
        dst_TKEEP => grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TKEEP,
        dst_TSTRB => grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TSTRB,
        dst_TUSER => grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TUSER,
        dst_TLAST => grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TLAST,
        dst_TID => grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TID,
        dst_TDEST => grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDEST,
        height => empty_408_reg_459,
        width => empty_407_reg_454,
        height_new => empty_406_reg_449,
        width_new => empty_405_reg_444,
        threshold => empty_reg_439,
        length_r => grp_process_ORB_8_0_1080_1920_1_s_fu_247_length_r,
        cntTree_address0 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address0,
        cntTree_ce0 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce0,
        cntTree_d0 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_d0,
        cntTree_q0 => ap_const_lv32_0,
        cntTree_we0 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_we0,
        cntTree_address1 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address1,
        cntTree_ce1 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce1,
        cntTree_d1 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_d1,
        cntTree_q1 => cntTree_q1,
        cntTree_we1 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_we1,
        idxTree_address0 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_address0,
        idxTree_ce0 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_ce0,
        idxTree_d0 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_d0,
        idxTree_q0 => ap_const_lv32_0,
        idxTree_we0 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_we0,
        idxTree_address1 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_address1,
        idxTree_ce1 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_ce1,
        idxTree_d1 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_d1,
        idxTree_q1 => ap_const_lv32_0,
        idxTree_we1 => grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_we1,
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        height_ap_vld => ap_const_logic_1,
        width_ap_vld => ap_const_logic_1,
        height_new_ap_vld => ap_const_logic_1,
        width_new_ap_vld => ap_const_logic_1,
        threshold_ap_vld => ap_const_logic_1,
        ap_start => grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start,
        src_TVALID => src_TVALID_int_regslice,
        src_TREADY => grp_process_ORB_8_0_1080_1920_1_s_fu_247_src_TREADY,
        dst_TVALID => grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID,
        dst_TREADY => grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TREADY,
        length_r_ap_vld => grp_process_ORB_8_0_1080_1920_1_s_fu_247_length_r_ap_vld,
        ap_done => grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done,
        ap_ready => grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready,
        ap_idle => grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_idle,
        ap_continue => grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_continue);

    mul_8ns_8ns_15_1_1_U1676 : component ORB_accel_mul_8ns_8ns_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 15)
    port map (
        din0 => mul_ln354_fu_366_p0,
        din1 => mul_ln354_fu_366_p1,
        dout => mul_ln354_fu_366_p2);

    regslice_both_src_V_data_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => src_TDATA,
        vld_in => src_TVALID,
        ack_in => regslice_both_src_V_data_V_U_ack_in,
        data_out => src_TDATA_int_regslice,
        vld_out => src_TVALID_int_regslice,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_src_V_data_V_U_apdone_blk);

    regslice_both_src_V_keep_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => src_TKEEP,
        vld_in => src_TVALID,
        ack_in => regslice_both_src_V_keep_V_U_ack_in,
        data_out => src_TKEEP_int_regslice,
        vld_out => regslice_both_src_V_keep_V_U_vld_out,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_src_V_keep_V_U_apdone_blk);

    regslice_both_src_V_strb_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => src_TSTRB,
        vld_in => src_TVALID,
        ack_in => regslice_both_src_V_strb_V_U_ack_in,
        data_out => src_TSTRB_int_regslice,
        vld_out => regslice_both_src_V_strb_V_U_vld_out,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_src_V_strb_V_U_apdone_blk);

    regslice_both_src_V_user_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => src_TUSER,
        vld_in => src_TVALID,
        ack_in => regslice_both_src_V_user_V_U_ack_in,
        data_out => src_TUSER_int_regslice,
        vld_out => regslice_both_src_V_user_V_U_vld_out,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_src_V_user_V_U_apdone_blk);

    regslice_both_src_V_last_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => src_TLAST,
        vld_in => src_TVALID,
        ack_in => regslice_both_src_V_last_V_U_ack_in,
        data_out => src_TLAST_int_regslice,
        vld_out => regslice_both_src_V_last_V_U_vld_out,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_src_V_last_V_U_apdone_blk);

    regslice_both_src_V_id_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => src_TID,
        vld_in => src_TVALID,
        ack_in => regslice_both_src_V_id_V_U_ack_in,
        data_out => src_TID_int_regslice,
        vld_out => regslice_both_src_V_id_V_U_vld_out,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_src_V_id_V_U_apdone_blk);

    regslice_both_src_V_dest_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => src_TDEST,
        vld_in => src_TVALID,
        ack_in => regslice_both_src_V_dest_V_U_ack_in,
        data_out => src_TDEST_int_regslice,
        vld_out => regslice_both_src_V_dest_V_U_vld_out,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_src_V_dest_V_U_apdone_blk);

    regslice_both_dst_V_data_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 296)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => dst_TDATA_int_regslice,
        vld_in => dst_TVALID_int_regslice,
        ack_in => dst_TREADY_int_regslice,
        data_out => dst_TDATA,
        vld_out => regslice_both_dst_V_data_V_U_vld_out,
        ack_out => dst_TREADY,
        apdone_blk => regslice_both_dst_V_data_V_U_apdone_blk);

    regslice_both_dst_V_keep_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 37)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => dst_TKEEP_int_regslice,
        vld_in => dst_TVALID_int_regslice,
        ack_in => regslice_both_dst_V_keep_V_U_ack_in_dummy,
        data_out => dst_TKEEP,
        vld_out => regslice_both_dst_V_keep_V_U_vld_out,
        ack_out => dst_TREADY,
        apdone_blk => regslice_both_dst_V_keep_V_U_apdone_blk);

    regslice_both_dst_V_strb_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 37)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => dst_TSTRB_int_regslice,
        vld_in => dst_TVALID_int_regslice,
        ack_in => regslice_both_dst_V_strb_V_U_ack_in_dummy,
        data_out => dst_TSTRB,
        vld_out => regslice_both_dst_V_strb_V_U_vld_out,
        ack_out => dst_TREADY,
        apdone_blk => regslice_both_dst_V_strb_V_U_apdone_blk);

    regslice_both_dst_V_user_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => dst_TUSER_int_regslice,
        vld_in => dst_TVALID_int_regslice,
        ack_in => regslice_both_dst_V_user_V_U_ack_in_dummy,
        data_out => dst_TUSER,
        vld_out => regslice_both_dst_V_user_V_U_vld_out,
        ack_out => dst_TREADY,
        apdone_blk => regslice_both_dst_V_user_V_U_apdone_blk);

    regslice_both_dst_V_last_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => dst_TLAST_int_regslice,
        vld_in => dst_TVALID_int_regslice,
        ack_in => regslice_both_dst_V_last_V_U_ack_in_dummy,
        data_out => dst_TLAST,
        vld_out => regslice_both_dst_V_last_V_U_vld_out,
        ack_out => dst_TREADY,
        apdone_blk => regslice_both_dst_V_last_V_U_apdone_blk);

    regslice_both_dst_V_id_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => dst_TID_int_regslice,
        vld_in => dst_TVALID_int_regslice,
        ack_in => regslice_both_dst_V_id_V_U_ack_in_dummy,
        data_out => dst_TID,
        vld_out => regslice_both_dst_V_id_V_U_vld_out,
        ack_out => dst_TREADY,
        apdone_blk => regslice_both_dst_V_id_V_U_apdone_blk);

    regslice_both_dst_V_dest_V_U : component ORB_accel_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => dst_TDEST_int_regslice,
        vld_in => dst_TVALID_int_regslice,
        ack_in => regslice_both_dst_V_dest_V_U_ack_in_dummy,
        data_out => dst_TDEST,
        vld_out => regslice_both_dst_V_dest_V_U_vld_out,
        ack_out => dst_TREADY,
        apdone_blk => regslice_both_dst_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state7))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state7)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state7);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done <= ap_const_logic_0;
                elsif ((grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready <= ap_const_logic_0;
                elsif ((grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
                    grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready = ap_const_logic_1)) then 
                    grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    cnt_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                cnt_fu_130 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln353_fu_400_p2 = ap_const_lv1_1) and (icmp_ln352_fu_378_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                cnt_fu_130 <= cnt_9_fu_410_p2;
            end if; 
        end if;
    end process;

    i_reg_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln352_fu_378_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                i_reg_236 <= add_ln352_fu_372_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_reg_236 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    val_reg_225_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                val_reg_225 <= ap_const_lv9_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                val_reg_225 <= add_ln351_reg_474;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (regslice_both_dst_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                add_ln351_reg_474 <= add_ln351_fu_336_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln351_fu_342_p2 = ap_const_lv1_0))) then
                cntTree_addr_reg_487 <= p_cast_fu_358_p1(8 - 1 downto 0);
                empty_409_reg_482 <= empty_409_fu_352_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                cntTree_load_reg_497 <= cntTree_q0;
                mul_ln354_reg_492 <= mul_ln354_fu_366_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln353_fu_400_p2 = ap_const_lv1_1) and (icmp_ln352_fu_378_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                dst_axi_last_V_reg_520 <= dst_axi_last_V_fu_405_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                empty_405_reg_444 <= empty_405_fu_307_p1;
                empty_406_reg_449 <= empty_406_fu_312_p1;
                empty_407_reg_454 <= empty_407_fu_317_p1;
                empty_408_reg_459 <= empty_408_fu_322_p1;
                empty_reg_439 <= empty_fu_302_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln352_fu_378_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln353_reg_516 <= icmp_ln353_fu_400_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln353_reg_516_pp0_iter1_reg <= icmp_ln353_reg_516;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_length_r_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                nFeatures_fu_134 <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_length_r;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                nFeatures_load_reg_464 <= nFeatures_fu_134;
                sub9_reg_469 <= sub9_fu_330_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_state5, regslice_both_dst_V_data_V_U_apdone_blk, icmp_ln351_fu_342_p2, ap_enable_reg_pp0_iter0, icmp_ln352_fu_378_p2, ap_block_pp0_stage0_subdone, ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln351_fu_342_p2 = ap_const_lv1_1) and (regslice_both_dst_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln351_fu_342_p2 = ap_const_lv1_0) and (regslice_both_dst_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln352_fu_378_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln352_fu_378_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln351_fu_336_p2 <= std_logic_vector(unsigned(val_reg_225) + unsigned(ap_const_lv9_1));
    add_ln352_fu_372_p2 <= std_logic_vector(unsigned(i_reg_236) + unsigned(ap_const_lv32_1));
    add_ln354_fu_390_p2 <= std_logic_vector(unsigned(mul_ln354_reg_492) + unsigned(trunc_ln354_fu_386_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(6);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(7);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln353_reg_516, ap_enable_reg_pp0_iter2, icmp_ln353_reg_516_pp0_iter1_reg, dst_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((icmp_ln353_reg_516_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (dst_TREADY_int_regslice = ap_const_logic_0)) or ((icmp_ln353_reg_516 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (dst_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln353_reg_516, ap_enable_reg_pp0_iter2, icmp_ln353_reg_516_pp0_iter1_reg, ap_block_state8_io, ap_block_state9_io, dst_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state9_io) or ((icmp_ln353_reg_516_pp0_iter1_reg = ap_const_lv1_1) and (dst_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state8_io) or ((icmp_ln353_reg_516 = ap_const_lv1_1) and (dst_TREADY_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln353_reg_516, ap_enable_reg_pp0_iter2, icmp_ln353_reg_516_pp0_iter1_reg, ap_block_state8_io, ap_block_state9_io, dst_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state9_io) or ((icmp_ln353_reg_516_pp0_iter1_reg = ap_const_lv1_1) and (dst_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state8_io) or ((icmp_ln353_reg_516 = ap_const_lv1_1) and (dst_TREADY_int_regslice = ap_const_logic_0)))));
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready, ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done)
    begin
                ap_block_state3_on_subcall_done <= ((ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready and ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done) = ap_const_logic_0);
    end process;

        ap_block_state7_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_io_assign_proc : process(icmp_ln353_reg_516, dst_TREADY_int_regslice)
    begin
                ap_block_state8_io <= ((icmp_ln353_reg_516 = ap_const_lv1_1) and (dst_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state8_pp0_stage0_iter1_assign_proc : process(icmp_ln353_reg_516, dst_TREADY_int_regslice)
    begin
                ap_block_state8_pp0_stage0_iter1 <= ((icmp_ln353_reg_516 = ap_const_lv1_1) and (dst_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state9_io_assign_proc : process(icmp_ln353_reg_516_pp0_iter1_reg, dst_TREADY_int_regslice)
    begin
                ap_block_state9_io <= ((icmp_ln353_reg_516_pp0_iter1_reg = ap_const_lv1_1) and (dst_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state9_pp0_stage0_iter2_assign_proc : process(icmp_ln353_reg_516_pp0_iter1_reg, dst_TREADY_int_regslice)
    begin
                ap_block_state9_pp0_stage0_iter2 <= ((icmp_ln353_reg_516_pp0_iter1_reg = ap_const_lv1_1) and (dst_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state7_assign_proc : process(icmp_ln352_fu_378_p2)
    begin
        if ((icmp_ln352_fu_378_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state7 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state5, regslice_both_dst_V_data_V_U_apdone_blk, icmp_ln351_fu_342_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln351_fu_342_p2 = ap_const_lv1_1) and (regslice_both_dst_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, regslice_both_dst_V_data_V_U_apdone_blk, icmp_ln351_fu_342_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln351_fu_342_p2 = ap_const_lv1_1) and (regslice_both_dst_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done <= (grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done or ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done);
    ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready <= (grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready or ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready);

    cntTree_address0_assign_proc : process(ap_CS_fsm_state5, cntTree_addr_reg_487, grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address0, ap_CS_fsm_state10, ap_CS_fsm_state3, p_cast_fu_358_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            cntTree_address0 <= cntTree_addr_reg_487;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            cntTree_address0 <= p_cast_fu_358_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            cntTree_address0 <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address0;
        else 
            cntTree_address0 <= "XXXXXXXX";
        end if; 
    end process;


    cntTree_ce0_assign_proc : process(ap_CS_fsm_state5, regslice_both_dst_V_data_V_U_apdone_blk, grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce0, ap_CS_fsm_state10, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (regslice_both_dst_V_data_V_U_apdone_blk = ap_const_logic_0)))) then 
            cntTree_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            cntTree_ce0 <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce0;
        else 
            cntTree_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    cntTree_ce1_assign_proc : process(grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce1, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            cntTree_ce1 <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce1;
        else 
            cntTree_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    cntTree_d0_assign_proc : process(grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_d0, ap_CS_fsm_state10, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            cntTree_d0 <= ap_const_lv32_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            cntTree_d0 <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_d0;
        else 
            cntTree_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    cntTree_we0_assign_proc : process(grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_we0, ap_CS_fsm_state10, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            cntTree_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            cntTree_we0 <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_we0;
        else 
            cntTree_we0 <= ap_const_logic_0;
        end if; 
    end process;

    cnt_9_fu_410_p2 <= std_logic_vector(unsigned(cnt_fu_130) + unsigned(ap_const_lv32_1));

    dst_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln353_reg_516, ap_enable_reg_pp0_iter2, icmp_ln353_reg_516_pp0_iter1_reg, dst_TREADY_int_regslice)
    begin
        if ((((icmp_ln353_reg_516_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((icmp_ln353_reg_516 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            dst_TDATA_blk_n <= dst_TREADY_int_regslice;
        else 
            dst_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dst_TDATA_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln353_reg_516, sext_ln301_fu_421_p1, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDATA, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID, ap_CS_fsm_state3, ap_block_pp0_stage0_01001)
    begin
        if (((icmp_ln353_reg_516 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_TDATA_int_regslice <= sext_ln301_fu_421_p1;
        elsif (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            dst_TDATA_int_regslice <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDATA;
        else 
            dst_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dst_TDEST_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln353_reg_516, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDEST, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID, ap_CS_fsm_state3, ap_block_pp0_stage0_01001)
    begin
        if (((icmp_ln353_reg_516 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_TDEST_int_regslice <= ap_const_lv1_0;
        elsif (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            dst_TDEST_int_regslice <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDEST;
        else 
            dst_TDEST_int_regslice <= "X";
        end if; 
    end process;


    dst_TID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln353_reg_516, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TID, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID, ap_CS_fsm_state3, ap_block_pp0_stage0_01001)
    begin
        if (((icmp_ln353_reg_516 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_TID_int_regslice <= ap_const_lv1_0;
        elsif (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            dst_TID_int_regslice <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TID;
        else 
            dst_TID_int_regslice <= "X";
        end if; 
    end process;


    dst_TKEEP_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln353_reg_516, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TKEEP, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID, ap_CS_fsm_state3, ap_block_pp0_stage0_01001)
    begin
        if (((icmp_ln353_reg_516 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_TKEEP_int_regslice <= ap_const_lv37_1FFFFFFFFF;
        elsif (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            dst_TKEEP_int_regslice <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TKEEP;
        else 
            dst_TKEEP_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dst_TLAST_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln353_reg_516, dst_axi_last_V_reg_520, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TLAST, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID, ap_CS_fsm_state3, ap_block_pp0_stage0_01001)
    begin
        if (((icmp_ln353_reg_516 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_TLAST_int_regslice <= dst_axi_last_V_reg_520;
        elsif (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            dst_TLAST_int_regslice <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TLAST;
        else 
            dst_TLAST_int_regslice <= "X";
        end if; 
    end process;


    dst_TSTRB_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln353_reg_516, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TSTRB, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID, ap_CS_fsm_state3, ap_block_pp0_stage0_01001)
    begin
        if (((icmp_ln353_reg_516 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_TSTRB_int_regslice <= ap_const_lv37_0;
        elsif (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            dst_TSTRB_int_regslice <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TSTRB;
        else 
            dst_TSTRB_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dst_TUSER_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln353_reg_516, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TUSER, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID, ap_CS_fsm_state3, ap_block_pp0_stage0_01001)
    begin
        if (((icmp_ln353_reg_516 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_TUSER_int_regslice <= ap_const_lv1_0;
        elsif (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            dst_TUSER_int_regslice <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TUSER;
        else 
            dst_TUSER_int_regslice <= "X";
        end if; 
    end process;

    dst_TVALID <= regslice_both_dst_V_data_V_U_vld_out;

    dst_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln353_reg_516, ap_block_pp0_stage0_11001, grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID, ap_CS_fsm_state3)
    begin
        if (((icmp_ln353_reg_516 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_TVALID_int_regslice <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dst_TVALID_int_regslice <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID;
        else 
            dst_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    dst_axi_last_V_fu_405_p2 <= "1" when (cnt_fu_130 = sub9_reg_469) else "0";
    empty_405_fu_307_p1 <= width_new(11 - 1 downto 0);
    empty_406_fu_312_p1 <= height_new(11 - 1 downto 0);
    empty_407_fu_317_p1 <= width(11 - 1 downto 0);
    empty_408_fu_322_p1 <= height(11 - 1 downto 0);
    empty_409_fu_352_p2 <= (trunc_ln351_fu_348_p1 xor ap_const_lv8_FF);
    empty_fu_302_p1 <= threshold(8 - 1 downto 0);

    grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_continue_assign_proc : process(ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_continue <= ap_const_logic_1;
        else 
            grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start_reg;
    grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TREADY <= (dst_TREADY_int_regslice and ap_CS_fsm_state3);
    icmp_ln351_fu_342_p2 <= "1" when (val_reg_225 = ap_const_lv9_100) else "0";
    icmp_ln352_fu_378_p2 <= "1" when (i_reg_236 = cntTree_load_reg_497) else "0";
    icmp_ln353_fu_400_p2 <= "1" when (signed(cnt_fu_130) < signed(nFeatures_load_reg_464)) else "0";

    idxTree_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter0, grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_address0, ap_CS_fsm_state3, zext_ln354_1_fu_395_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            idxTree_address0 <= zext_ln354_1_fu_395_p1(15 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            idxTree_address0 <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_address0;
        else 
            idxTree_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    idxTree_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_ce0, ap_CS_fsm_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            idxTree_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            idxTree_ce0 <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_ce0;
        else 
            idxTree_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    idxTree_we0_assign_proc : process(grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            idxTree_we0 <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_we0;
        else 
            idxTree_we0 <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln354_fu_366_p0 <= mul_ln354_fu_366_p00(8 - 1 downto 0);
    mul_ln354_fu_366_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_409_reg_482),15));
    mul_ln354_fu_366_p1 <= ap_const_lv15_64(8 - 1 downto 0);
    p_cast_fu_358_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_409_fu_352_p2),64));
        sext_ln301_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(idxTree_q0),296));

    src_TREADY <= regslice_both_src_V_data_V_U_ack_in;

    src_TREADY_int_regslice_assign_proc : process(grp_process_ORB_8_0_1080_1920_1_s_fu_247_src_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            src_TREADY_int_regslice <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_src_TREADY;
        else 
            src_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    sub9_fu_330_p2 <= std_logic_vector(unsigned(nFeatures_fu_134) + unsigned(ap_const_lv32_FFFFFFFF));
    trunc_ln351_fu_348_p1 <= val_reg_225(8 - 1 downto 0);
    trunc_ln354_fu_386_p1 <= i_reg_236(15 - 1 downto 0);
    zext_ln354_1_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln354_fu_390_p2),64));
end behav;
