// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ORB_accel_generic_atan2_20_20_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in1,
        in2,
        ap_return
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_state4 = 4'd4;
parameter    ap_ST_fsm_state5 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [19:0] in1;
input  [19:0] in2;
output  [19:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[19:0] ap_return;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [6:0] circ_table_arctan_128_V56_address0;
reg    circ_table_arctan_128_V56_ce0;
wire   [125:0] circ_table_arctan_128_V56_q0;
reg   [4:0] n_reg_101;
reg   [26:0] empty_reg_112;
reg   [26:0] empty_112_reg_124;
reg   [26:0] p_Val2_7_reg_133;
wire   [0:0] icmp_ln1494_fu_177_p2;
reg   [0:0] icmp_ln1494_reg_575;
wire   [1:0] signin1_fu_193_p3;
reg   [1:0] signin1_reg_580;
wire   [0:0] icmp_ln1494_1_fu_201_p2;
reg   [0:0] icmp_ln1494_1_reg_585;
wire   [1:0] signin2_fu_217_p3;
reg   [1:0] signin2_reg_590;
wire   [0:0] icmp_ln870_fu_225_p2;
reg   [0:0] icmp_ln870_reg_595;
wire   [0:0] and_ln608_fu_231_p2;
reg   [0:0] and_ln608_reg_600;
wire   [0:0] icmp_ln870_4_fu_237_p2;
reg   [0:0] icmp_ln870_4_reg_604;
wire   [0:0] and_ln612_fu_243_p2;
reg   [0:0] and_ln612_reg_609;
wire   [0:0] and_ln616_fu_255_p2;
reg   [0:0] and_ln616_reg_613;
wire   [0:0] icmp_ln870_6_fu_261_p2;
reg   [0:0] icmp_ln870_6_reg_617;
wire   [0:0] and_ln620_fu_267_p2;
reg   [0:0] and_ln620_reg_622;
wire   [0:0] icmp_ln1498_2_fu_273_p2;
reg   [0:0] icmp_ln1498_2_reg_626;
wire   [0:0] icmp_ln1494_2_fu_315_p2;
reg   [0:0] icmp_ln1494_2_reg_630;
wire  signed [26:0] sext_ln669_fu_345_p1;
wire  signed [26:0] sext_ln664_fu_357_p1;
wire   [4:0] add_ln87_fu_361_p2;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln87_fu_367_p2;
reg   [0:0] icmp_ln87_reg_650;
wire   [0:0] tmp_51_fu_378_p3;
reg   [0:0] tmp_51_reg_654;
wire   [26:0] ty_fu_426_p3;
wire   [26:0] tx_fu_434_p3;
wire   [26:0] tz_fu_468_p3;
reg    ap_enable_reg_pp0_iter1;
wire   [19:0] select_ln631_fu_568_p3;
wire    ap_CS_fsm_state5;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire    ap_block_pp0_stage0;
reg   [19:0] ap_phi_mux_agg_result_0_phi_fu_150_p20;
reg   [19:0] agg_result_0_reg_142;
wire    ap_CS_fsm_state4;
wire   [0:0] and_ln681_fu_488_p2;
wire   [0:0] icmp_ln684_fu_496_p2;
wire   [0:0] and_ln687_fu_502_p2;
wire   [63:0] zext_ln87_fu_373_p1;
wire  signed [19:0] icmp_ln1494_fu_177_p0;
wire  signed [19:0] icmp_ln1498_fu_183_p0;
wire   [0:0] icmp_ln1498_fu_183_p2;
wire   [1:0] zext_ln601_fu_189_p1;
wire  signed [19:0] icmp_ln1494_1_fu_201_p0;
wire  signed [19:0] icmp_ln1498_1_fu_207_p0;
wire   [0:0] icmp_ln1498_1_fu_207_p2;
wire   [1:0] zext_ln602_fu_213_p1;
wire   [0:0] icmp_ln870_5_fu_249_p2;
wire  signed [19:0] icmp_ln1498_2_fu_273_p0;
wire  signed [19:0] icmp_ln1498_2_fu_273_p1;
wire  signed [19:0] sext_ln703_fu_279_p0;
wire  signed [20:0] sext_ln703_fu_279_p1;
wire   [20:0] r_V_fu_283_p2;
wire  signed [19:0] sext_ln703_1_fu_297_p0;
wire  signed [20:0] sext_ln703_1_fu_297_p1;
wire   [20:0] r_V_10_fu_301_p2;
wire   [20:0] in1abs_V_fu_289_p3;
wire   [20:0] in2abs_V_fu_307_p3;
wire   [25:0] shl_ln728_1_fu_329_p3;
wire   [25:0] shl_ln_fu_321_p3;
wire   [25:0] y_V_fu_337_p3;
wire   [25:0] x_V_fu_349_p3;
wire   [26:0] zext_ln1333_fu_386_p1;
wire   [26:0] r_V_12_fu_396_p2;
wire   [26:0] r_V_11_fu_390_p2;
wire   [26:0] add_ln703_2_fu_420_p2;
wire   [26:0] sub_ln703_fu_408_p2;
wire   [26:0] sub_ln703_3_fu_414_p2;
wire   [26:0] add_ln703_fu_402_p2;
wire   [23:0] tmp_fu_442_p4;
wire   [26:0] zext_ln708_fu_452_p1;
wire   [26:0] sub_ln703_4_fu_462_p2;
wire   [26:0] add_ln703_1_fu_456_p2;
wire   [26:0] z_V_1_fu_475_p2;
wire   [1:0] or_ln684_fu_492_p2;
wire   [26:0] z_V_2_fu_481_p3;
wire   [26:0] r_fu_517_p2;
wire   [26:0] ret_V_20_fu_534_p2;
wire   [26:0] ret_V_fu_551_p2;
reg   [19:0] ap_return_preg;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_504;
reg    ap_condition_508;
reg    ap_condition_501;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_return_preg = 20'd0;
end

ORB_accel_generic_atan2_20_20_s_circ_table_arctan_128_V56 #(
    .DataWidth( 126 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
circ_table_arctan_128_V56_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(circ_table_arctan_128_V56_address0),
    .ce0(circ_table_arctan_128_V56_ce0),
    .q0(circ_table_arctan_128_V56_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (icmp_ln1498_2_fu_273_p2 == 1'd0) & (1'd0 == and_ln620_fu_267_p2) & (1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (icmp_ln1498_2_fu_273_p2 == 1'd0) & (1'd0 == and_ln620_fu_267_p2) & (1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 20'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_return_preg <= ap_phi_mux_agg_result_0_phi_fu_150_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (icmp_ln1498_2_fu_273_p2 == 1'd1) & (1'd0 == and_ln620_fu_267_p2) & (1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (icmp_ln1494_fu_177_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        agg_result_0_reg_142 <= 20'd102943;
    end else if (((ap_start == 1'b1) & (1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln620_fu_267_p2))) begin
        agg_result_0_reg_142 <= 20'd842688;
    end else if (((ap_start == 1'b1) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln616_fu_255_p2))) begin
        agg_result_0_reg_142 <= 20'd205887;
    end else if (((ap_start == 1'b1) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln612_fu_243_p2))) begin
        agg_result_0_reg_142 <= 20'd411774;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln608_fu_231_p2))) begin
        agg_result_0_reg_142 <= 20'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        agg_result_0_reg_142 <= select_ln631_fu_568_p3;
    end else if (((icmp_ln1498_2_reg_626 == 1'd0) & (1'd0 == and_ln620_reg_622) & (1'd0 == and_ln616_reg_613) & (1'd0 == and_ln612_reg_609) & (1'd0 == and_ln608_reg_600) & (1'd0 == and_ln687_fu_502_p2) & (1'd0 == and_ln681_fu_488_p2) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln684_fu_496_p2 == 1'd0))) begin
        agg_result_0_reg_142 <= {{z_V_2_fu_481_p3[26:7]}};
    end else if (((icmp_ln1498_2_reg_626 == 1'd0) & (1'd0 == and_ln620_reg_622) & (1'd0 == and_ln616_reg_613) & (1'd0 == and_ln612_reg_609) & (1'd0 == and_ln608_reg_600) & (1'd0 == and_ln681_fu_488_p2) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln684_fu_496_p2 == 1'd0) & (1'd1 == and_ln687_fu_502_p2))) begin
        agg_result_0_reg_142 <= {{r_fu_517_p2[26:7]}};
    end else if (((icmp_ln1498_2_reg_626 == 1'd0) & (1'd0 == and_ln620_reg_622) & (1'd0 == and_ln616_reg_613) & (1'd0 == and_ln612_reg_609) & (1'd0 == and_ln608_reg_600) & (1'd0 == and_ln681_fu_488_p2) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln684_fu_496_p2 == 1'd1))) begin
        agg_result_0_reg_142 <= {{ret_V_20_fu_534_p2[26:7]}};
    end else if (((icmp_ln1498_2_reg_626 == 1'd0) & (1'd0 == and_ln620_reg_622) & (1'd0 == and_ln616_reg_613) & (1'd0 == and_ln612_reg_609) & (1'd0 == and_ln608_reg_600) & (1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln681_fu_488_p2))) begin
        agg_result_0_reg_142 <= {{ret_V_fu_551_p2[26:7]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (icmp_ln1498_2_fu_273_p2 == 1'd0) & (1'd0 == and_ln620_fu_267_p2) & (1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_112_reg_124 <= sext_ln664_fu_357_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln87_fu_367_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_112_reg_124 <= tx_fu_434_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (icmp_ln1498_2_fu_273_p2 == 1'd0) & (1'd0 == and_ln620_fu_267_p2) & (1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_reg_112 <= 27'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln87_reg_650 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_reg_112 <= tz_fu_468_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (icmp_ln1498_2_fu_273_p2 == 1'd0) & (1'd0 == and_ln620_fu_267_p2) & (1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        n_reg_101 <= 5'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln87_fu_367_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        n_reg_101 <= add_ln87_fu_361_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (icmp_ln1498_2_fu_273_p2 == 1'd0) & (1'd0 == and_ln620_fu_267_p2) & (1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        p_Val2_7_reg_133 <= sext_ln669_fu_345_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln87_fu_367_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_7_reg_133 <= ty_fu_426_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        and_ln608_reg_600 <= and_ln608_fu_231_p2;
        icmp_ln1494_1_reg_585 <= icmp_ln1494_1_fu_201_p2;
        icmp_ln1494_reg_575 <= icmp_ln1494_fu_177_p2;
        icmp_ln870_reg_595 <= icmp_ln870_fu_225_p2;
        signin1_reg_580 <= signin1_fu_193_p3;
        signin2_reg_590 <= signin2_fu_217_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        and_ln612_reg_609 <= and_ln612_fu_243_p2;
        icmp_ln870_4_reg_604 <= icmp_ln870_4_fu_237_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        and_ln616_reg_613 <= and_ln616_fu_255_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        and_ln620_reg_622 <= and_ln620_fu_267_p2;
        icmp_ln870_6_reg_617 <= icmp_ln870_6_fu_261_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1498_2_fu_273_p2 == 1'd0) & (1'd0 == and_ln620_fu_267_p2) & (1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln1494_2_reg_630 <= icmp_ln1494_2_fu_315_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln620_fu_267_p2) & (1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln1498_2_reg_626 <= icmp_ln1498_2_fu_273_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln87_reg_650 <= icmp_ln87_fu_367_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln87_fu_367_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_51_reg_654 <= p_Val2_7_reg_133[32'd26];
    end
end

always @ (*) begin
    if ((icmp_ln87_fu_367_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_501)) begin
        if ((1'b1 == ap_condition_508)) begin
            ap_phi_mux_agg_result_0_phi_fu_150_p20 = {{z_V_2_fu_481_p3[26:7]}};
        end else if ((1'b1 == ap_condition_504)) begin
            ap_phi_mux_agg_result_0_phi_fu_150_p20 = {{r_fu_517_p2[26:7]}};
        end else if (((1'd0 == and_ln681_fu_488_p2) & (icmp_ln684_fu_496_p2 == 1'd1))) begin
            ap_phi_mux_agg_result_0_phi_fu_150_p20 = {{ret_V_20_fu_534_p2[26:7]}};
        end else if ((1'd1 == and_ln681_fu_488_p2)) begin
            ap_phi_mux_agg_result_0_phi_fu_150_p20 = {{ret_V_fu_551_p2[26:7]}};
        end else begin
            ap_phi_mux_agg_result_0_phi_fu_150_p20 = agg_result_0_reg_142;
        end
    end else begin
        ap_phi_mux_agg_result_0_phi_fu_150_p20 = agg_result_0_reg_142;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_return = ap_phi_mux_agg_result_0_phi_fu_150_p20;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        circ_table_arctan_128_V56_ce0 = 1'b1;
    end else begin
        circ_table_arctan_128_V56_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (icmp_ln1498_2_fu_273_p2 == 1'd1) & (1'd0 == and_ln620_fu_267_p2) & (1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (icmp_ln1494_fu_177_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((ap_start == 1'b1) & (icmp_ln1498_2_fu_273_p2 == 1'd0) & (1'd0 == and_ln620_fu_267_p2) & (1'd0 == and_ln616_fu_255_p2) & (1'd0 == and_ln612_fu_243_p2) & (1'd0 == and_ln608_fu_231_p2) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((1'd1 == and_ln608_fu_231_p2) | ((1'd1 == and_ln612_fu_243_p2) | ((1'd1 == and_ln616_fu_255_p2) | ((1'd1 == and_ln620_fu_267_p2) | ((icmp_ln1498_2_fu_273_p2 == 1'd1) & (icmp_ln1494_fu_177_p2 == 1'd1)))))))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln87_fu_367_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln87_fu_367_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln703_1_fu_456_p2 = (zext_ln708_fu_452_p1 + empty_reg_112);

assign add_ln703_2_fu_420_p2 = (r_V_11_fu_390_p2 + p_Val2_7_reg_133);

assign add_ln703_fu_402_p2 = (r_V_12_fu_396_p2 + empty_112_reg_124);

assign add_ln87_fu_361_p2 = (n_reg_101 + 5'd1);

assign and_ln608_fu_231_p2 = (icmp_ln870_fu_225_p2 & icmp_ln1494_1_fu_201_p2);

assign and_ln612_fu_243_p2 = (icmp_ln870_fu_225_p2 & icmp_ln870_4_fu_237_p2);

assign and_ln616_fu_255_p2 = (icmp_ln870_5_fu_249_p2 & icmp_ln1494_fu_177_p2);

assign and_ln620_fu_267_p2 = (icmp_ln870_6_fu_261_p2 & icmp_ln870_5_fu_249_p2);

assign and_ln681_fu_488_p2 = (icmp_ln870_4_reg_604 & icmp_ln1494_reg_575);

assign and_ln687_fu_502_p2 = (icmp_ln870_6_reg_617 & icmp_ln1494_1_reg_585);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_501 = ((icmp_ln1498_2_reg_626 == 1'd0) & (1'd0 == and_ln620_reg_622) & (1'd0 == and_ln616_reg_613) & (1'd0 == and_ln612_reg_609) & (1'd0 == and_ln608_reg_600) & (1'b1 == ap_CS_fsm_state4));
end

always @ (*) begin
    ap_condition_504 = ((1'd0 == and_ln681_fu_488_p2) & (icmp_ln684_fu_496_p2 == 1'd0) & (1'd1 == and_ln687_fu_502_p2));
end

always @ (*) begin
    ap_condition_508 = ((1'd0 == and_ln687_fu_502_p2) & (1'd0 == and_ln681_fu_488_p2) & (icmp_ln684_fu_496_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign circ_table_arctan_128_V56_address0 = zext_ln87_fu_373_p1;

assign icmp_ln1494_1_fu_201_p0 = in2;

assign icmp_ln1494_1_fu_201_p2 = (($signed(icmp_ln1494_1_fu_201_p0) > $signed(20'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_315_p2 = (($signed(in1abs_V_fu_289_p3) > $signed(in2abs_V_fu_307_p3)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_177_p0 = in1;

assign icmp_ln1494_fu_177_p2 = (($signed(icmp_ln1494_fu_177_p0) > $signed(20'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1498_1_fu_207_p0 = in2;

assign icmp_ln1498_1_fu_207_p2 = ((icmp_ln1498_1_fu_207_p0 == 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_2_fu_273_p0 = in1;

assign icmp_ln1498_2_fu_273_p1 = in2;

assign icmp_ln1498_2_fu_273_p2 = ((icmp_ln1498_2_fu_273_p0 == icmp_ln1498_2_fu_273_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_fu_183_p0 = in1;

assign icmp_ln1498_fu_183_p2 = ((icmp_ln1498_fu_183_p0 == 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln684_fu_496_p2 = ((or_ln684_fu_492_p2 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln870_4_fu_237_p2 = ((signin2_fu_217_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln870_5_fu_249_p2 = ((signin2_fu_217_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln870_6_fu_261_p2 = ((signin1_fu_193_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln870_fu_225_p2 = ((signin1_fu_193_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_367_p2 = ((n_reg_101 == 5'd27) ? 1'b1 : 1'b0);

assign in1abs_V_fu_289_p3 = ((icmp_ln870_6_fu_261_p2[0:0] == 1'b1) ? r_V_fu_283_p2 : sext_ln703_fu_279_p1);

assign in2abs_V_fu_307_p3 = ((icmp_ln870_4_fu_237_p2[0:0] == 1'b1) ? r_V_10_fu_301_p2 : sext_ln703_1_fu_297_p1);

assign or_ln684_fu_492_p2 = (signin2_reg_590 | signin1_reg_580);

assign r_V_10_fu_301_p2 = ($signed(21'd0) - $signed(sext_ln703_1_fu_297_p1));

assign r_V_11_fu_390_p2 = $signed(empty_112_reg_124) >>> zext_ln1333_fu_386_p1;

assign r_V_12_fu_396_p2 = $signed(p_Val2_7_reg_133) >>> zext_ln1333_fu_386_p1;

assign r_V_fu_283_p2 = ($signed(21'd0) - $signed(sext_ln703_fu_279_p1));

assign r_fu_517_p2 = (27'd0 - z_V_2_fu_481_p3);

assign ret_V_20_fu_534_p2 = ($signed(z_V_2_fu_481_p3) + $signed(27'd81510592));

assign ret_V_fu_551_p2 = (27'd52707136 - z_V_2_fu_481_p3);

assign select_ln631_fu_568_p3 = ((icmp_ln870_reg_595[0:0] == 1'b1) ? 20'd0 : 20'd739744);

assign sext_ln664_fu_357_p1 = $signed(x_V_fu_349_p3);

assign sext_ln669_fu_345_p1 = $signed(y_V_fu_337_p3);

assign sext_ln703_1_fu_297_p0 = in2;

assign sext_ln703_1_fu_297_p1 = sext_ln703_1_fu_297_p0;

assign sext_ln703_fu_279_p0 = in1;

assign sext_ln703_fu_279_p1 = sext_ln703_fu_279_p0;

assign shl_ln728_1_fu_329_p3 = {{in2abs_V_fu_307_p3}, {5'd0}};

assign shl_ln_fu_321_p3 = {{in1abs_V_fu_289_p3}, {5'd0}};

assign signin1_fu_193_p3 = ((icmp_ln1494_fu_177_p2[0:0] == 1'b1) ? 2'd2 : zext_ln601_fu_189_p1);

assign signin2_fu_217_p3 = ((icmp_ln1494_1_fu_201_p2[0:0] == 1'b1) ? 2'd2 : zext_ln602_fu_213_p1);

assign sub_ln703_3_fu_414_p2 = (empty_112_reg_124 - r_V_12_fu_396_p2);

assign sub_ln703_4_fu_462_p2 = (empty_reg_112 - zext_ln708_fu_452_p1);

assign sub_ln703_fu_408_p2 = (p_Val2_7_reg_133 - r_V_11_fu_390_p2);

assign tmp_51_fu_378_p3 = p_Val2_7_reg_133[32'd26];

assign tmp_fu_442_p4 = {{circ_table_arctan_128_V56_q0[125:102]}};

assign tx_fu_434_p3 = ((tmp_51_fu_378_p3[0:0] == 1'b1) ? sub_ln703_3_fu_414_p2 : add_ln703_fu_402_p2);

assign ty_fu_426_p3 = ((tmp_51_fu_378_p3[0:0] == 1'b1) ? add_ln703_2_fu_420_p2 : sub_ln703_fu_408_p2);

assign tz_fu_468_p3 = ((tmp_51_reg_654[0:0] == 1'b1) ? sub_ln703_4_fu_462_p2 : add_ln703_1_fu_456_p2);

assign x_V_fu_349_p3 = ((icmp_ln1494_2_fu_315_p2[0:0] == 1'b1) ? shl_ln_fu_321_p3 : shl_ln728_1_fu_329_p3);

assign y_V_fu_337_p3 = ((icmp_ln1494_2_fu_315_p2[0:0] == 1'b1) ? shl_ln728_1_fu_329_p3 : shl_ln_fu_321_p3);

assign z_V_1_fu_475_p2 = (27'd26353568 - empty_reg_112);

assign z_V_2_fu_481_p3 = ((icmp_ln1494_2_reg_630[0:0] == 1'b1) ? z_V_1_fu_475_p2 : empty_reg_112);

assign zext_ln1333_fu_386_p1 = n_reg_101;

assign zext_ln601_fu_189_p1 = icmp_ln1498_fu_183_p2;

assign zext_ln602_fu_213_p1 = icmp_ln1498_1_fu_207_p2;

assign zext_ln708_fu_452_p1 = tmp_fu_442_p4;

assign zext_ln87_fu_373_p1 = n_reg_101;

endmodule //ORB_accel_generic_atan2_20_20_s
