// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ORB_accel_ORB_accel,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.273750,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=208,HLS_SYN_DSP=0,HLS_SYN_FF=50255,HLS_SYN_LUT=42365,HLS_VERSION=2020_2}" *)

module ORB_accel (
        ap_clk,
        ap_rst_n,
        src_TDATA,
        src_TVALID,
        src_TREADY,
        src_TKEEP,
        src_TSTRB,
        src_TUSER,
        src_TLAST,
        src_TID,
        src_TDEST,
        dst_TDATA,
        dst_TVALID,
        dst_TREADY,
        dst_TKEEP,
        dst_TSTRB,
        dst_TUSER,
        dst_TLAST,
        dst_TID,
        dst_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_pp0_stage0 = 8'd64;
parameter    ap_ST_fsm_state10 = 8'd128;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [7:0] src_TDATA;
input   src_TVALID;
output   src_TREADY;
input  [0:0] src_TKEEP;
input  [0:0] src_TSTRB;
input  [0:0] src_TUSER;
input  [0:0] src_TLAST;
input  [0:0] src_TID;
input  [0:0] src_TDEST;
output  [295:0] dst_TDATA;
output   dst_TVALID;
input   dst_TREADY;
output  [36:0] dst_TKEEP;
output  [36:0] dst_TSTRB;
output  [0:0] dst_TUSER;
output  [0:0] dst_TLAST;
output  [0:0] dst_TID;
output  [0:0] dst_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] height;
wire   [31:0] width;
wire   [31:0] height_new;
wire   [31:0] width_new;
wire   [31:0] threshold;
reg   [7:0] cntTree_address0;
reg    cntTree_ce0;
reg    cntTree_we0;
reg   [31:0] cntTree_d0;
wire   [31:0] cntTree_q0;
reg    cntTree_ce1;
wire   [31:0] cntTree_q1;
reg   [14:0] idxTree_address0;
reg    idxTree_ce0;
reg    idxTree_we0;
wire   [31:0] idxTree_q0;
reg    dst_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln353_reg_516;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln353_reg_516_pp0_iter1_reg;
reg   [31:0] i_reg_236;
wire   [7:0] empty_fu_302_p1;
reg   [7:0] empty_reg_439;
wire    ap_CS_fsm_state2;
wire   [10:0] empty_405_fu_307_p1;
reg   [10:0] empty_405_reg_444;
wire   [10:0] empty_406_fu_312_p1;
reg   [10:0] empty_406_reg_449;
wire   [10:0] empty_407_fu_317_p1;
reg   [10:0] empty_407_reg_454;
wire   [10:0] empty_408_fu_322_p1;
reg   [10:0] empty_408_reg_459;
reg   [31:0] nFeatures_load_reg_464;
wire    ap_CS_fsm_state4;
wire   [31:0] sub9_fu_330_p2;
reg   [31:0] sub9_reg_469;
wire   [8:0] add_ln351_fu_336_p2;
reg   [8:0] add_ln351_reg_474;
wire    ap_CS_fsm_state5;
wire    regslice_both_dst_V_data_V_U_apdone_blk;
wire   [7:0] empty_409_fu_352_p2;
reg   [7:0] empty_409_reg_482;
wire   [0:0] icmp_ln351_fu_342_p2;
reg   [7:0] cntTree_addr_reg_487;
wire   [14:0] mul_ln354_fu_366_p2;
reg   [14:0] mul_ln354_reg_492;
wire    ap_CS_fsm_state6;
reg   [31:0] cntTree_load_reg_497;
wire   [31:0] add_ln352_fu_372_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state7_pp0_stage0_iter0;
reg    ap_block_state8_pp0_stage0_iter1;
reg    ap_block_state8_io;
reg    ap_block_state9_pp0_stage0_iter2;
reg    ap_block_state9_io;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln352_fu_378_p2;
wire   [0:0] icmp_ln353_fu_400_p2;
wire   [0:0] dst_axi_last_V_fu_405_p2;
reg   [0:0] dst_axi_last_V_reg_520;
wire  signed [295:0] sext_ln301_fu_421_p1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state7;
wire   [295:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDATA;
wire   [36:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TKEEP;
wire   [36:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TSTRB;
wire   [0:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TUSER;
wire   [0:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TLAST;
wire   [0:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TID;
wire   [0:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDEST;
wire   [31:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_length_r;
wire   [7:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address0;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce0;
wire   [31:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_d0;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_we0;
wire   [7:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address1;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce1;
wire   [31:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_d1;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_we1;
wire   [14:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_address0;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_ce0;
wire   [31:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_d0;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_we0;
wire   [14:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_address1;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_ce1;
wire   [31:0] grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_d1;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_we1;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_src_TREADY;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TREADY;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_length_r_ap_vld;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready;
wire    grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_idle;
reg    grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_continue;
reg   [8:0] val_reg_225;
wire    ap_CS_fsm_state10;
reg    grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready;
wire    ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done;
reg    ap_block_state3_on_subcall_done;
reg    ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready;
reg    ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done;
reg   [31:0] nFeatures_fu_134;
wire   [63:0] p_cast_fu_358_p1;
wire   [63:0] zext_ln354_1_fu_395_p1;
reg   [31:0] cnt_fu_130;
wire   [31:0] cnt_9_fu_410_p2;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] trunc_ln351_fu_348_p1;
wire   [7:0] mul_ln354_fu_366_p0;
wire   [7:0] mul_ln354_fu_366_p1;
wire   [14:0] trunc_ln354_fu_386_p1;
wire   [14:0] add_ln354_fu_390_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_src_V_data_V_U_apdone_blk;
wire   [7:0] src_TDATA_int_regslice;
wire    src_TVALID_int_regslice;
reg    src_TREADY_int_regslice;
wire    regslice_both_src_V_data_V_U_ack_in;
wire    regslice_both_src_V_keep_V_U_apdone_blk;
wire   [0:0] src_TKEEP_int_regslice;
wire    regslice_both_src_V_keep_V_U_vld_out;
wire    regslice_both_src_V_keep_V_U_ack_in;
wire    regslice_both_src_V_strb_V_U_apdone_blk;
wire   [0:0] src_TSTRB_int_regslice;
wire    regslice_both_src_V_strb_V_U_vld_out;
wire    regslice_both_src_V_strb_V_U_ack_in;
wire    regslice_both_src_V_user_V_U_apdone_blk;
wire   [0:0] src_TUSER_int_regslice;
wire    regslice_both_src_V_user_V_U_vld_out;
wire    regslice_both_src_V_user_V_U_ack_in;
wire    regslice_both_src_V_last_V_U_apdone_blk;
wire   [0:0] src_TLAST_int_regslice;
wire    regslice_both_src_V_last_V_U_vld_out;
wire    regslice_both_src_V_last_V_U_ack_in;
wire    regslice_both_src_V_id_V_U_apdone_blk;
wire   [0:0] src_TID_int_regslice;
wire    regslice_both_src_V_id_V_U_vld_out;
wire    regslice_both_src_V_id_V_U_ack_in;
wire    regslice_both_src_V_dest_V_U_apdone_blk;
wire   [0:0] src_TDEST_int_regslice;
wire    regslice_both_src_V_dest_V_U_vld_out;
wire    regslice_both_src_V_dest_V_U_ack_in;
reg   [295:0] dst_TDATA_int_regslice;
reg    dst_TVALID_int_regslice;
wire    dst_TREADY_int_regslice;
wire    regslice_both_dst_V_data_V_U_vld_out;
wire    regslice_both_dst_V_keep_V_U_apdone_blk;
reg   [36:0] dst_TKEEP_int_regslice;
wire    regslice_both_dst_V_keep_V_U_ack_in_dummy;
wire    regslice_both_dst_V_keep_V_U_vld_out;
wire    regslice_both_dst_V_strb_V_U_apdone_blk;
reg   [36:0] dst_TSTRB_int_regslice;
wire    regslice_both_dst_V_strb_V_U_ack_in_dummy;
wire    regslice_both_dst_V_strb_V_U_vld_out;
wire    regslice_both_dst_V_user_V_U_apdone_blk;
reg   [0:0] dst_TUSER_int_regslice;
wire    regslice_both_dst_V_user_V_U_ack_in_dummy;
wire    regslice_both_dst_V_user_V_U_vld_out;
wire    regslice_both_dst_V_last_V_U_apdone_blk;
reg   [0:0] dst_TLAST_int_regslice;
wire    regslice_both_dst_V_last_V_U_ack_in_dummy;
wire    regslice_both_dst_V_last_V_U_vld_out;
wire    regslice_both_dst_V_id_V_U_apdone_blk;
reg   [0:0] dst_TID_int_regslice;
wire    regslice_both_dst_V_id_V_U_ack_in_dummy;
wire    regslice_both_dst_V_id_V_U_vld_out;
wire    regslice_both_dst_V_dest_V_U_apdone_blk;
reg   [0:0] dst_TDEST_int_regslice;
wire    regslice_both_dst_V_dest_V_U_ack_in_dummy;
wire    regslice_both_dst_V_dest_V_U_vld_out;
wire   [14:0] mul_ln354_fu_366_p00;
wire    ap_ce_reg;
wire   [31:0] ap_return;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready = 1'b0;
#0 ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done = 1'b0;
end

ORB_accel_cntTree #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
cntTree_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(cntTree_address0),
    .ce0(cntTree_ce0),
    .we0(cntTree_we0),
    .d0(cntTree_d0),
    .q0(cntTree_q0),
    .address1(grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address1),
    .ce1(cntTree_ce1),
    .q1(cntTree_q1)
);

ORB_accel_idxTree #(
    .DataWidth( 32 ),
    .AddressRange( 25600 ),
    .AddressWidth( 15 ))
idxTree_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(idxTree_address0),
    .ce0(idxTree_ce0),
    .we0(idxTree_we0),
    .d0(grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_d0),
    .q0(idxTree_q0)
);

ORB_accel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(nFeatures_fu_134),
    .height(height),
    .width(width),
    .height_new(height_new),
    .width_new(width_new),
    .threshold(threshold)
);

ORB_accel_process_ORB_8_0_1080_1920_1_s grp_process_ORB_8_0_1080_1920_1_s_fu_247(
    .src_TDATA(src_TDATA_int_regslice),
    .src_TKEEP(src_TKEEP_int_regslice),
    .src_TSTRB(src_TSTRB_int_regslice),
    .src_TUSER(src_TUSER_int_regslice),
    .src_TLAST(src_TLAST_int_regslice),
    .src_TID(src_TID_int_regslice),
    .src_TDEST(src_TDEST_int_regslice),
    .dst_TDATA(grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDATA),
    .dst_TKEEP(grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TKEEP),
    .dst_TSTRB(grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TSTRB),
    .dst_TUSER(grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TUSER),
    .dst_TLAST(grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TLAST),
    .dst_TID(grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TID),
    .dst_TDEST(grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDEST),
    .height(empty_408_reg_459),
    .width(empty_407_reg_454),
    .height_new(empty_406_reg_449),
    .width_new(empty_405_reg_444),
    .threshold(empty_reg_439),
    .length_r(grp_process_ORB_8_0_1080_1920_1_s_fu_247_length_r),
    .cntTree_address0(grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address0),
    .cntTree_ce0(grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce0),
    .cntTree_d0(grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_d0),
    .cntTree_q0(32'd0),
    .cntTree_we0(grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_we0),
    .cntTree_address1(grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address1),
    .cntTree_ce1(grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce1),
    .cntTree_d1(grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_d1),
    .cntTree_q1(cntTree_q1),
    .cntTree_we1(grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_we1),
    .idxTree_address0(grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_address0),
    .idxTree_ce0(grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_ce0),
    .idxTree_d0(grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_d0),
    .idxTree_q0(32'd0),
    .idxTree_we0(grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_we0),
    .idxTree_address1(grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_address1),
    .idxTree_ce1(grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_ce1),
    .idxTree_d1(grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_d1),
    .idxTree_q1(32'd0),
    .idxTree_we1(grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_we1),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .height_ap_vld(1'b1),
    .width_ap_vld(1'b1),
    .height_new_ap_vld(1'b1),
    .width_new_ap_vld(1'b1),
    .threshold_ap_vld(1'b1),
    .ap_start(grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start),
    .src_TVALID(src_TVALID_int_regslice),
    .src_TREADY(grp_process_ORB_8_0_1080_1920_1_s_fu_247_src_TREADY),
    .dst_TVALID(grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID),
    .dst_TREADY(grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TREADY),
    .length_r_ap_vld(grp_process_ORB_8_0_1080_1920_1_s_fu_247_length_r_ap_vld),
    .ap_done(grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done),
    .ap_ready(grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready),
    .ap_idle(grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_idle),
    .ap_continue(grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_continue)
);

ORB_accel_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U1676(
    .din0(mul_ln354_fu_366_p0),
    .din1(mul_ln354_fu_366_p1),
    .dout(mul_ln354_fu_366_p2)
);

ORB_accel_regslice_both #(
    .DataWidth( 8 ))
regslice_both_src_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TDATA),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_data_V_U_ack_in),
    .data_out(src_TDATA_int_regslice),
    .vld_out(src_TVALID_int_regslice),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_data_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TKEEP),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_keep_V_U_ack_in),
    .data_out(src_TKEEP_int_regslice),
    .vld_out(regslice_both_src_V_keep_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_keep_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TSTRB),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_strb_V_U_ack_in),
    .data_out(src_TSTRB_int_regslice),
    .vld_out(regslice_both_src_V_strb_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_strb_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TUSER),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_user_V_U_ack_in),
    .data_out(src_TUSER_int_regslice),
    .vld_out(regslice_both_src_V_user_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_user_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TLAST),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_last_V_U_ack_in),
    .data_out(src_TLAST_int_regslice),
    .vld_out(regslice_both_src_V_last_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_last_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TID),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_id_V_U_ack_in),
    .data_out(src_TID_int_regslice),
    .vld_out(regslice_both_src_V_id_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_id_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TDEST),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_dest_V_U_ack_in),
    .data_out(src_TDEST_int_regslice),
    .vld_out(regslice_both_src_V_dest_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_dest_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 296 ))
regslice_both_dst_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dst_TDATA_int_regslice),
    .vld_in(dst_TVALID_int_regslice),
    .ack_in(dst_TREADY_int_regslice),
    .data_out(dst_TDATA),
    .vld_out(regslice_both_dst_V_data_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_data_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 37 ))
regslice_both_dst_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dst_TKEEP_int_regslice),
    .vld_in(dst_TVALID_int_regslice),
    .ack_in(regslice_both_dst_V_keep_V_U_ack_in_dummy),
    .data_out(dst_TKEEP),
    .vld_out(regslice_both_dst_V_keep_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_keep_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 37 ))
regslice_both_dst_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dst_TSTRB_int_regslice),
    .vld_in(dst_TVALID_int_regslice),
    .ack_in(regslice_both_dst_V_strb_V_U_ack_in_dummy),
    .data_out(dst_TSTRB),
    .vld_out(regslice_both_dst_V_strb_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_strb_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dst_TUSER_int_regslice),
    .vld_in(dst_TVALID_int_regslice),
    .ack_in(regslice_both_dst_V_user_V_U_ack_in_dummy),
    .data_out(dst_TUSER),
    .vld_out(regslice_both_dst_V_user_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_user_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dst_TLAST_int_regslice),
    .vld_in(dst_TVALID_int_regslice),
    .ack_in(regslice_both_dst_V_last_V_U_ack_in_dummy),
    .data_out(dst_TLAST),
    .vld_out(regslice_both_dst_V_last_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_last_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dst_TID_int_regslice),
    .vld_in(dst_TVALID_int_regslice),
    .ack_in(regslice_both_dst_V_id_V_U_ack_in_dummy),
    .data_out(dst_TID),
    .vld_out(regslice_both_dst_V_id_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_id_V_U_apdone_blk)
);

ORB_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(dst_TDEST_int_regslice),
    .vld_in(dst_TVALID_int_regslice),
    .ack_in(regslice_both_dst_V_dest_V_U_ack_in_dummy),
    .data_out(dst_TDEST),
    .vld_out(regslice_both_dst_V_dest_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state7))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state7)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state7);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done <= 1'b0;
        end else if ((grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done == 1'b1)) begin
            ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready <= 1'b0;
        end else if ((grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) | ((ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state3)))) begin
            grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start_reg <= 1'b1;
        end else if ((grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready == 1'b1)) begin
            grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        cnt_fu_130 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln353_fu_400_p2 == 1'd1) & (icmp_ln352_fu_378_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        cnt_fu_130 <= cnt_9_fu_410_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln352_fu_378_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        i_reg_236 <= add_ln352_fu_372_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_reg_236 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        val_reg_225 <= 9'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        val_reg_225 <= add_ln351_reg_474;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (regslice_both_dst_V_data_V_U_apdone_blk == 1'b0))) begin
        add_ln351_reg_474 <= add_ln351_fu_336_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln351_fu_342_p2 == 1'd0))) begin
        cntTree_addr_reg_487 <= p_cast_fu_358_p1;
        empty_409_reg_482 <= empty_409_fu_352_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        cntTree_load_reg_497 <= cntTree_q0;
        mul_ln354_reg_492 <= mul_ln354_fu_366_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln353_fu_400_p2 == 1'd1) & (icmp_ln352_fu_378_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_axi_last_V_reg_520 <= dst_axi_last_V_fu_405_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_405_reg_444 <= empty_405_fu_307_p1;
        empty_406_reg_449 <= empty_406_fu_312_p1;
        empty_407_reg_454 <= empty_407_fu_317_p1;
        empty_408_reg_459 <= empty_408_fu_322_p1;
        empty_reg_439 <= empty_fu_302_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln352_fu_378_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln353_reg_516 <= icmp_ln353_fu_400_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln353_reg_516_pp0_iter1_reg <= icmp_ln353_reg_516;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_length_r_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        nFeatures_fu_134 <= grp_process_ORB_8_0_1080_1920_1_s_fu_247_length_r;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        nFeatures_load_reg_464 <= nFeatures_fu_134;
        sub9_reg_469 <= sub9_fu_330_p2;
    end
end

always @ (*) begin
    if ((icmp_ln352_fu_378_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state7 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln351_fu_342_p2 == 1'd1) & (regslice_both_dst_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln351_fu_342_p2 == 1'd1) & (regslice_both_dst_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        cntTree_address0 = cntTree_addr_reg_487;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        cntTree_address0 = p_cast_fu_358_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        cntTree_address0 = grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_address0;
    end else begin
        cntTree_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state5) & (regslice_both_dst_V_data_V_U_apdone_blk == 1'b0)))) begin
        cntTree_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        cntTree_ce0 = grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce0;
    end else begin
        cntTree_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        cntTree_ce1 = grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_ce1;
    end else begin
        cntTree_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        cntTree_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        cntTree_d0 = grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_d0;
    end else begin
        cntTree_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        cntTree_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        cntTree_we0 = grp_process_ORB_8_0_1080_1920_1_s_fu_247_cntTree_we0;
    end else begin
        cntTree_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln353_reg_516_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((icmp_ln353_reg_516 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        dst_TDATA_blk_n = dst_TREADY_int_regslice;
    end else begin
        dst_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln353_reg_516 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_TDATA_int_regslice = sext_ln301_fu_421_p1;
    end else if (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        dst_TDATA_int_regslice = grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDATA;
    end else begin
        dst_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln353_reg_516 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_TDEST_int_regslice = 1'd0;
    end else if (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        dst_TDEST_int_regslice = grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TDEST;
    end else begin
        dst_TDEST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln353_reg_516 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_TID_int_regslice = 1'd0;
    end else if (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        dst_TID_int_regslice = grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TID;
    end else begin
        dst_TID_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln353_reg_516 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_TKEEP_int_regslice = 37'd137438953471;
    end else if (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        dst_TKEEP_int_regslice = grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TKEEP;
    end else begin
        dst_TKEEP_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln353_reg_516 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_TLAST_int_regslice = dst_axi_last_V_reg_520;
    end else if (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        dst_TLAST_int_regslice = grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TLAST;
    end else begin
        dst_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln353_reg_516 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_TSTRB_int_regslice = 37'd0;
    end else if (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        dst_TSTRB_int_regslice = grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TSTRB;
    end else begin
        dst_TSTRB_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln353_reg_516 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_TUSER_int_regslice = 1'd0;
    end else if (((grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        dst_TUSER_int_regslice = grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TUSER;
    end else begin
        dst_TUSER_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln353_reg_516 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dst_TVALID_int_regslice = grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TVALID;
    end else begin
        dst_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
        grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_continue = 1'b1;
    end else begin
        grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        idxTree_address0 = zext_ln354_1_fu_395_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        idxTree_address0 = grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_address0;
    end else begin
        idxTree_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        idxTree_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        idxTree_ce0 = grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_ce0;
    end else begin
        idxTree_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        idxTree_we0 = grp_process_ORB_8_0_1080_1920_1_s_fu_247_idxTree_we0;
    end else begin
        idxTree_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        src_TREADY_int_regslice = grp_process_ORB_8_0_1080_1920_1_s_fu_247_src_TREADY;
    end else begin
        src_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln351_fu_342_p2 == 1'd1) & (regslice_both_dst_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln351_fu_342_p2 == 1'd0) & (regslice_both_dst_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln352_fu_378_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln352_fu_378_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln351_fu_336_p2 = (val_reg_225 + 9'd1);

assign add_ln352_fu_372_p2 = (i_reg_236 + 32'd1);

assign add_ln354_fu_390_p2 = (mul_ln354_reg_492 + trunc_ln354_fu_386_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln353_reg_516_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (dst_TREADY_int_regslice == 1'b0)) | ((icmp_ln353_reg_516 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (dst_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state9_io) | ((icmp_ln353_reg_516_pp0_iter1_reg == 1'd1) & (dst_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state8_io) | ((icmp_ln353_reg_516 == 1'd1) & (dst_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state9_io) | ((icmp_ln353_reg_516_pp0_iter1_reg == 1'd1) & (dst_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state8_io) | ((icmp_ln353_reg_516 == 1'd1) & (dst_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = ((ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready & ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done) == 1'b0);
end

assign ap_block_state7_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((icmp_ln353_reg_516 == 1'd1) & (dst_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp0_stage0_iter1 = ((icmp_ln353_reg_516 == 1'd1) & (dst_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state9_io = ((icmp_ln353_reg_516_pp0_iter1_reg == 1'd1) & (dst_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter2 = ((icmp_ln353_reg_516_pp0_iter1_reg == 1'd1) & (dst_TREADY_int_regslice == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done = (grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done | ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_done);

assign ap_sync_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready = (grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready | ap_sync_reg_grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_ready);

assign cnt_9_fu_410_p2 = (cnt_fu_130 + 32'd1);

assign dst_TVALID = regslice_both_dst_V_data_V_U_vld_out;

assign dst_axi_last_V_fu_405_p2 = ((cnt_fu_130 == sub9_reg_469) ? 1'b1 : 1'b0);

assign empty_405_fu_307_p1 = width_new[10:0];

assign empty_406_fu_312_p1 = height_new[10:0];

assign empty_407_fu_317_p1 = width[10:0];

assign empty_408_fu_322_p1 = height[10:0];

assign empty_409_fu_352_p2 = (trunc_ln351_fu_348_p1 ^ 8'd255);

assign empty_fu_302_p1 = threshold[7:0];

assign grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start = grp_process_ORB_8_0_1080_1920_1_s_fu_247_ap_start_reg;

assign grp_process_ORB_8_0_1080_1920_1_s_fu_247_dst_TREADY = (dst_TREADY_int_regslice & ap_CS_fsm_state3);

assign icmp_ln351_fu_342_p2 = ((val_reg_225 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln352_fu_378_p2 = ((i_reg_236 == cntTree_load_reg_497) ? 1'b1 : 1'b0);

assign icmp_ln353_fu_400_p2 = (($signed(cnt_fu_130) < $signed(nFeatures_load_reg_464)) ? 1'b1 : 1'b0);

assign mul_ln354_fu_366_p0 = mul_ln354_fu_366_p00;

assign mul_ln354_fu_366_p00 = empty_409_reg_482;

assign mul_ln354_fu_366_p1 = 15'd100;

assign p_cast_fu_358_p1 = empty_409_fu_352_p2;

assign sext_ln301_fu_421_p1 = $signed(idxTree_q0);

assign src_TREADY = regslice_both_src_V_data_V_U_ack_in;

assign sub9_fu_330_p2 = ($signed(nFeatures_fu_134) + $signed(32'd4294967295));

assign trunc_ln351_fu_348_p1 = val_reg_225[7:0];

assign trunc_ln354_fu_386_p1 = i_reg_236[14:0];

assign zext_ln354_1_fu_395_p1 = add_ln354_fu_390_p2;


// synthesis translate_off
`include "ORB_accel_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //ORB_accel

